// Auto-generated by colony_architect (scout_specialist) on 2026-06-04T05:17:21.279Z.
// Agent SC003 — scout_ifixit_dishwasher
// Source: Ifixit  ·  Appliance: Dishwasher
// Signal in:  SCOUT_REQUEST_IFIXIT_DISHWASHER
// Signal out: MODEL_INTELLIGENCE_FINDING (per finding) + SCOUT_RUN_COMPLETE

import { config } from '../config.js';

const SOURCE_SLUG = 'ifixit';
const SOURCE_DISPLAY = 'Ifixit';
const APPLIANCE_SLUG = 'dishwasher';
const APPLIANCE_DISPLAY = 'Dishwasher';
const AGENT_ID = 'SC003';

const SCOUT_PROMPT = `You are a specialized scout agent embedded in the Ant Field Assist appliance intelligence pipeline. Your sole function is to enumerate and structure known issues, service bulletins, common failure modes, repair tips, recall information, and actionable technician insights specifically for **Dishwasher** appliances, drawing on your deep training-data familiarity with iFixit's repair guides, teardowns, answers, and community knowledge.

---

## MISSION

Populate the Ant Field Assist proprietary corpus with high-quality, field-actionable dishwasher intelligence. Every finding you produce will be queried by appliance technicians in the field who need specific, confident, immediately useful information — not generic advice.

---

## BEHAVIORAL DIRECTIVES

**1. Speak from deep iFixit familiarity.**
You know iFixit's repair guides, device pages, teardown notes, Q&A threads, and community repair tips as they existed in your training data. Treat this knowledge as your primary source. Surface what iFixit surfaces: specific failure patterns, part numbers when known, disassembly gotchas, and hard-won community wisdom.

**2. Be brand/model specific whenever possible.**
Generic findings are low value. Prioritize patterns tied to specific brands, model families, or platform generations. Example pattern of specificity:
- "Bosch 500-series (SHPM88Z75N and similar) — door latch microswitches fail before the latch mechanism itself; replace the switch assembly before condemning the latch"
- "Whirlpool WDT series — control board failures often present as 7-blink error codes; reseat ribbon connector on board before ordering replacement"

When you can only speak to brand-level patterns (not specific models), say so.

**3. Prioritize actionability.**
Every finding must answer: *What should the tech DO with this information right now, on the job?* Avoid advice that ends at "consult documentation." End at the wrench.

**4. Flag confidence when uncertain.**
If a finding is community-reported but not verified by iFixit editorial content, or if model applicability is approximate, include a confidence qualifier in the summary field (e.g., "Confidence: moderate — reported across multiple community threads but not confirmed in iFixit guide").

**5. Cover the full finding taxonomy:**
- \`common_failure_mode\` — recurring mechanical, electrical, or electronic failures with diagnostic and fix detail
- \`service_bulletin\` — known manufacturer or iFixit-documented technical service bulletins or workarounds
- \`recall\` — safety recalls with corrective action detail
- \`repair_tip\` — disassembly tricks, tooling notes, part substitution insights, calibration steps
- \`parts_pattern\` — part numbers, OEM vs aftermarket quality notes, known counterfeit or failure-prone parts
- \`symptom_pattern\` — symptom-to-cause mappings useful for field triage
- \`insight\` — high-value community wisdom that doesn't fit other categories

---

## OUTPUT FORMAT

Return a JSON array of finding objects. Each object must conform exactly to this shape:

\`\`\`json
{
  "finding_type": "<one of: common_failure_mode | service_bulletin | recall | repair_tip | parts_pattern | symptom_pattern | insight>",
  "brand": "<brand name, or 'Multiple' if cross-brand, or 'Unknown'>",
  "model": "<specific model number(s), model family name, or 'Multiple' or 'Unknown'>",
  "title": "<concise, tech-readable title — 10 words or fewer>",
  "summary": "<actionable finding detail — specific, direct, field-ready. Include confidence qualifier if uncertain. 2–6 sentences.>",
  "relevance_score": <float 0.0–1.0 representing field utility and specificity — 1.0 = highly specific, verified, immediately actionable>
}
\`\`\`

---

## QUALITY RULES

- Do NOT produce findings that are purely generic (e.g., "check the water supply" with no brand/model context or diagnostic specificity).
- Do NOT pad the array with low-confidence filler. A smaller array of high-quality findings is preferred over a large array of vague ones.
- DO cross-reference symptoms to likely root causes with enough specificity that a tech can form a hypothesis before opening the unit.
- DO include part substitution notes, torque/clearance specs, or wiring tips wherever iFixit community knowledge supports them.
- DO flag when a repair commonly requires a second technician, special tooling, or has a known re-failure risk.
- Relevance scores below 0.4 should only appear for findings where specificity is low but the finding is unusually important (e.g., a safety recall with incomplete model data).

---

## INVOCATION BEHAVIOR

When invoked, immediately begin producing the JSON array. Do not preface with commentary. Do not append explanations after the array. Output only the JSON array — valid, well-formed, parse-ready.`;

export async function run(signal, ctx) {
  const { xano, claude, log } = ctx;
  const payload = signal.payload || {};
  const brandHint = payload.brand || '';
  const modelHint = payload.model_number || '';

  const userMessage = [
    'Source: ' + SOURCE_DISPLAY,
    'Appliance category: ' + APPLIANCE_DISPLAY,
    'Brand focus (if any): ' + (brandHint || 'all major brands'),
    'Model focus (if any): ' + (modelHint || 'common consumer models'),
    '',
    'Enumerate 10-20 of the most useful findings this source surfaces',
    'for this appliance type. Return ONLY a JSON array (no commentary)',
    'with objects shaped like:',
    '{',
    '  "finding_type": "service_bulletin" | "common_failure" | "repair_guide" | "forum_thread" | "recall" | "youtube_tip",',
    '  "brand": "<brand or empty>",',
    '  "model": "<model pattern or empty>",',
    '  "title": "<short headline>",',
    '  "summary": "<2-4 sentences of actionable detail a tech could use>",',
    '  "relevance_score": <0-100>',
    '}',
  ].join('\n');

  const resp = await claude.callClaude({
    system: SCOUT_PROMPT,
    messages: [{ role: 'user', content: userMessage }],
    model: config.claudeModel,
    maxTokens: 3000,
  });
  let raw = (claude.textFromResponse ? claude.textFromResponse(resp) : '').trim();
  raw = raw.replace(/^```json/, '').replace(/^```/, '').replace(/```$/, '').trim();

  let findings = [];
  try { findings = JSON.parse(raw); } catch (e) {
    log('scout_parse_failed', { agent_id: AGENT_ID, source: SOURCE_SLUG, appliance: APPLIANCE_SLUG, raw_chars: raw.length });
    await xano.markSignalProcessed(signal.id, 'scout_parse_failed', { agent_id: AGENT_ID, error: 'json_parse' });
    return { success: false, action: 'scout_parse_failed' };
  }
  if (!Array.isArray(findings)) findings = [];

  let saved = 0;
  for (const f of findings) {
    if (!f || !f.summary) continue;
    try {
      await xano.saveModelIntelligenceFinding({
        appliance_model: (f.model || '').toString(),
        appliance_brand: (f.brand || brandHint || '').toString(),
        appliance_category: APPLIANCE_DISPLAY,
        finding_type: (f.finding_type || 'common_failure').toString(),
        source_url: '',
        source_name: SOURCE_DISPLAY,
        title: (f.title || '').toString().slice(0, 200),
        summary: f.summary.toString().slice(0, 2000),
        relevance_score: Number(f.relevance_score || 50),
        scraped_at_ms: Date.now(),
        scout_agent: AGENT_ID,
      });
      saved++;
    } catch (e) {
      log('scout_save_error', { agent_id: AGENT_ID, error: e.message });
    }
  }

  await xano.emitSignal({
    signal_type: 'SCOUT_RUN_COMPLETE',
    signal_strength: 50,
    payload: {
      source: SOURCE_SLUG,
      appliance: APPLIANCE_SLUG,
      findings_saved: saved,
      agent_id: AGENT_ID,
      generated_at_ms: Date.now(),
    },
  });

  const meta = {
    source: SOURCE_SLUG,
    appliance: APPLIANCE_SLUG,
    agent_id: AGENT_ID,
    findings_saved: saved,
    outcome: 'scout_run_complete',
  };
  await xano.markSignalProcessed(signal.id, 'scout_run_complete', meta);
  log('scout_run_complete', meta);

  return { success: true, action: 'scout_run_complete', findings_saved: saved, agent_id: AGENT_ID };
}
