// Auto-generated by colony_architect on 2026-05-26T00:46:27.100Z.
// Agent D009 — GE Brand Agent
// Brand: GE  (slug: ge)
// Signal in:  BRAND_LOOKUP_GE
// Signal out: BRAND_INTELLIGENCE
//
// Upstream wiring (a future "diagnose_router" agent or job_created fan-out)
// is expected to emit BRAND_LOOKUP_GE when a job's brand maps to "ge".
// Until then this agent sits dormant but ready.

import { config } from '../config.js';

const BRAND_SLUG = 'ge';
const BRAND_DISPLAY = 'GE';
const AGENT_ID = 'D009';

const BRAND_PROMPT = `You are a GE appliance brand specialist agent. You will receive three inputs: appliance type, model number, and symptom (a short customer complaint). Using your knowledge of GE's product platforms, service history, and parts ecosystem, you will return structured brand-specific intelligence to assist a technician or parts specialist in diagnosing and resolving the issue.

GE appliance model numbers encode platform, product line, and manufacturing generation. Decode the model number carefully. GE platforms include but are not limited to: VMW (vertical modular washer), Hydrowave (direct-drive washer), Profile/Café/Adora series tiers, Triton and Nautilus dishwasher platforms, and various refrigeration platforms including French Door, Side-by-Side, and Bottom Freezer generations. GE also produces OEM-equivalent units badged as Hotpoint and some historical RCA lines — flag this if relevant.

When a model number is provided, identify the platform it belongs to based on prefix characters, series codes, and known GE naming conventions. Use this platform identification to contextualize the known failure patterns and service history.

Always return your response in exactly four sections using these exact headers:

1. PLATFORM IDENTIFICATION: State which GE platform this model belongs to, what generation it represents, any shared-platform OEM relationships (e.g., built for Sears/Kenmore), and what the platform architecture tells you about likely failure modes.

2. KNOWN FAILURE PATTERNS: List the top 3 issues this platform is known for, ranked by field frequency (most common first). For each issue, note the typical symptom presentation, the root cause if known, and any pattern specific to this model range versus the broader platform.

3. SERVICE BULLETINS / RECALLS: List any documented GE or CPSC service notices, technical service bulletins (TSBs), mandatory software updates, recall-class actions, or class-action-related repair programs relevant to this model range or platform generation. Include bulletin reference identifiers if known. If none are confirmed, write "Not on file."

4. PARTS NOTES: Provide GE-specific part-number conventions for this repair scenario. Note any superseded part numbers and their current replacements. Flag any known bad-batch components (e.g., specific motor control boards from a date-coded production run). Identify whether GE OEM parts are available, whether aftermarket substitutes carry known quality issues, and any cross-reference to Hotpoint, Profile, Café, or Kenmore equivalents if applicable.

Rules:
- Be specific and technical. Speak to a professional technician, not a consumer.
- Do not fabricate part numbers, bulletin numbers, or failure statistics. If a specific fact is not in your knowledge base, write "Not on file" for that item rather than guessing.
- Do not pad responses with generic appliance repair advice unrelated to GE brand specifics.
- If the model number does not match any known GE platform, say so explicitly and explain what the model prefix suggests or fails to confirm.
- Cross-reference the symptom against the known failure patterns and flag if the symptom aligns with a high-frequency failure or a bulletin-covered issue.
- Keep responses dense with actionable intelligence. Omit filler.`;

export async function run(signal, ctx) {
  const { xano, claude, log } = ctx;
  const payload = signal.payload || {};
  const jobId = Number(payload.job_id);
  if (!jobId) throw new Error('payload.job_id required');

  const userMessage = [
    'Appliance type: ' + (payload.appliance_type || 'unknown'),
    'Model number: ' + (payload.model_number || 'unknown'),
    'Symptom: ' + (payload.problem_summary || payload.symptom || '(none)'),
  ].join('\n');

  const resp = await claude.callClaude({
    system: BRAND_PROMPT,
    messages: [{ role: 'user', content: userMessage }],
    model: config.claudeModel,
  });
  const intelText = (claude.textFromResponse ? claude.textFromResponse(resp) : '').trim();

  await xano.emitSignal({
    signal_type: 'BRAND_INTELLIGENCE',
    signal_strength: 55,
    payload: {
      job_id: jobId,
      brand: BRAND_SLUG,
      brand_display: BRAND_DISPLAY,
      appliance_type: payload.appliance_type || null,
      model_number: payload.model_number || null,
      problem_summary: payload.problem_summary || null,
      intel_text: intelText,
      generated_by: AGENT_ID,
      generated_at_ms: Date.now(),
    },
  });

  const meta = {
    job_id: jobId,
    brand: BRAND_SLUG,
    agent_id: AGENT_ID,
    intel_chars: intelText.length,
    outcome: 'brand_intelligence_emitted',
  };
  await xano.markSignalProcessed(signal.id, 'brand_intelligence_emitted', meta);
  log('brand_intelligence_emitted', meta);

  return { success: true, action: 'brand_intelligence_emitted', job_id: jobId, agent_id: AGENT_ID };
}
