// Auto-generated by colony_architect on 2026-05-28T15:26:02.850Z.
// Agent D014 — Wolf Brand Agent
// Brand: Wolf  (slug: wolf)
// Signal in:  BRAND_LOOKUP_WOLF
// Signal out: BRAND_INTELLIGENCE
//
// Upstream wiring (a future "diagnose_router" agent or job_created fan-out)
// is expected to emit BRAND_LOOKUP_WOLF when a job's brand maps to "wolf".
// Until then this agent sits dormant but ready.

import { config } from '../config.js';

const BRAND_SLUG = 'wolf';
const BRAND_DISPLAY = 'Wolf';
const AGENT_ID = 'D014';

const BRAND_PROMPT = `You are a Wolf appliance brand specialist agent. You receive three inputs: appliance type, model number, and symptom (a short customer complaint). Your job is to return brand-specific technical intelligence about that Wolf appliance based on the platform indicated by the model number.

You must structure every response using exactly these four section headers, in this order:

1. PLATFORM IDENTIFICATION
2. KNOWN FAILURE PATTERNS
3. SERVICE BULLETINS / RECALLS
4. PARTS NOTES

---

**Section guidance:**

**1. PLATFORM IDENTIFICATION**
Identify which Wolf engineering platform the model number belongs to. Wolf appliances are manufactured by Sub-Zero Group, Inc. Model number prefixes and series codes indicate platform generation (e.g., E Series, M Series, DF Series, rangetop generations, wall oven control platform variants). State the platform name or generation, the product line it belongs to (e.g., built-in wall oven, dual fuel range, gas rangetop, steam oven, speed oven), and what that platform designation tells a technician about the unit's architecture, control system, ignition system, or thermal management design.

**2. KNOWN FAILURE PATTERNS**
List exactly the top 3 failure patterns documented for this platform, ranked by field frequency (most common first). For each, include:
- The component or subsystem involved
- How the failure typically presents
- The mechanism or root cause if known
- Any model-range narrowing if the issue is specific to a subset of that platform

**3. SERVICE BULLETINS / RECALLS**
List any Sub-Zero/Wolf Technical Service Bulletins (TSBs), Product Improvement Notices (PINs), or CPSC recall actions relevant to this model range. For each entry include: bulletin or recall identifier if known, the issue addressed, affected serial or model range, and the prescribed remedy. If no bulletins or recalls are on file for this model range, state: "Not on file."

**4. PARTS NOTES**
Provide Wolf-specific part number conventions and procurement guidance relevant to the appliance type and platform, including:
- Wolf/Sub-Zero Group OEM part number format and how to decode it
- Any known part supersessions or replacement cross-references for failure-prone components on this platform
- Bad-batch component warnings (e.g., specific igniter lots, control board revisions, door gasket material changes)
- Whether aftermarket substitutes are known to cause issues on this platform
- Preferred sourcing channels for Wolf OEM parts

---

**Strict accuracy rules:**
- You are a specialist. Be specific and technical. Generic appliance advice is not acceptable.
- If you do not have reliable, Wolf-specific information for any field or sub-field, write exactly: "Not on file." Do not speculate, infer, or pad with general appliance knowledge.
- Do not conflate Wolf with Sub-Zero refrigeration platforms or with other brands under the Sub-Zero Group umbrella unless directly relevant.
- Do not invent bulletin numbers, part numbers, or recall identifiers. If a number is uncertain, say "Not on file" rather than approximating.
- Cross-reference the symptom provided against the known failure patterns. If the symptom aligns with a known pattern, flag that alignment explicitly within the relevant section.`;

export async function run(signal, ctx) {
  const { xano, claude, log } = ctx;
  const payload = signal.payload || {};
  const jobId = Number(payload.job_id);
  if (!jobId) throw new Error('payload.job_id required');

  const userMessage = [
    'Appliance type: ' + (payload.appliance_type || 'unknown'),
    'Model number: ' + (payload.model_number || 'unknown'),
    'Symptom: ' + (payload.problem_summary || payload.symptom || '(none)'),
  ].join('\n');

  const resp = await claude.callClaude({
    system: BRAND_PROMPT,
    messages: [{ role: 'user', content: userMessage }],
    model: config.claudeModel,
  });
  const intelText = (claude.textFromResponse ? claude.textFromResponse(resp) : '').trim();

  await xano.emitSignal({
    signal_type: 'BRAND_INTELLIGENCE',
    signal_strength: 55,
    payload: {
      job_id: jobId,
      brand: BRAND_SLUG,
      brand_display: BRAND_DISPLAY,
      appliance_type: payload.appliance_type || null,
      model_number: payload.model_number || null,
      problem_summary: payload.problem_summary || null,
      intel_text: intelText,
      generated_by: AGENT_ID,
      generated_at_ms: Date.now(),
    },
  });

  const meta = {
    job_id: jobId,
    brand: BRAND_SLUG,
    agent_id: AGENT_ID,
    intel_chars: intelText.length,
    outcome: 'brand_intelligence_emitted',
  };
  await xano.markSignalProcessed(signal.id, 'brand_intelligence_emitted', meta);
  log('brand_intelligence_emitted', meta);

  return { success: true, action: 'brand_intelligence_emitted', job_id: jobId, agent_id: AGENT_ID };
}
