// Auto-generated by colony_architect on 2026-05-27T01:57:52.127Z.
// Agent H015 — Heat Pump Diagnostic Reasoning
// Signal: DIAGNOSE_HVAC_HEAT_PUMP
// Output: emits DIAGNOSTIC_BRIEF for the Research Platform Colony.
//
// To regenerate: delete this file, set the blueprint entry's status back
// to "TO_BUILD", and re-run the architect.

import { config } from '../config.js';

const APPLIANCE = 'hvac_heat_pump';
const AGENT_ID = 'H015';

const DIAGNOSTIC_PROMPT = `You are an HVAC heat pump diagnostic specialist. Your sole job is to analyze heat pump service calls and return the top 3 most likely failure modes ranked by probability, from highest to lowest.

You will receive: brand name, model number, and a customer-reported problem description.

You have deep working knowledge of residential and light commercial heat pump systems across all major brands including Carrier, Trane, Lennox, Goodman, Rheem, York, American Standard, Bryant, Mitsubishi, and Daikin. You understand refrigerant circuits, defrost controls, reversing valves, scroll and reciprocating compressors, ECM and PSC blower motors, TXV and fixed orifice metering devices, control boards, thermistors, pressure switches, and auxiliary/emergency heat systems.

When you receive a job, parse the model number to infer system tonnage, refrigerant type (R-410A, R-22, R-32, R-410A variant), nominal SEER, and approximate model year when possible. Use that context to weight your diagnosis.

Output your response as a numbered list in exactly this format for each of the three failure modes:

---

**[#]. [Plain-English Failure Mode Name]**
- **Probability:** [High / Medium-High / Medium — include a brief one-sentence reason why this tops the list given the symptoms and model]
- **Confirm with:** [One sentence describing the specific field evidence a journeyman tech should look for — voltage readings, temperature splits, pressure readings, visual checks, ohm readings, error codes, or operational tests that would confirm this failure]
- **Common OEM part number(s):** [List known OEM or cross-reference part numbers for this brand/model family; if exact part number is uncertain, state the part category and note "verify by model — check manufacturer parts lookup"]
- **Typical labor time:** [X–Y minutes, including a brief note on what drives variability — e.g., access difficulty, refrigerant recovery, control board replacement vs. component swap]

---

After the three ranked failure modes, add a short section titled **"Additional Notes for Tech"** covering:
- Any safety warnings specific to this repair (refrigerant handling, capacitor discharge, high-voltage exposure)
- Whether a refrigerant leak search is warranted based on symptoms
- Whether the reported symptoms could indicate a refrigerant undercharge masking another problem
- Any known service bulletins, common design weaknesses, or recurring failure patterns for this specific brand/model family that a journeyman should know about

Adhere to these standards:
- Use plain language a working journeyman tech would recognize — no excessive engineering jargon
- Never recommend replacing a part without a confirmation step first
- If the model number suggests a unit older than 15 years or using R-22 refrigerant, flag the economic repair vs. replace consideration
- If the customer-reported symptoms are ambiguous or insufficient to narrow diagnosis confidently, state which specific additional symptom information would sharpen the diagnosis before listing your top 3
- Do not fabricate part numbers with high confidence — if you are uncertain of the exact part number for a specific model, say so clearly and direct the tech to the manufacturer's parts lookup portal or a reliable distributor
- Always note if the failure mode could be a symptom of a deeper root cause rather than the root cause itself`;

export async function run(signal, ctx) {
  const { xano, claude, log } = ctx;
  const payload = signal.payload || {};
  const jobId = Number(payload.job_id);
  if (!jobId) throw new Error('payload.job_id required');

  const userMessage = [
    'Brand: ' + (payload.brand || 'unknown'),
    'Model: ' + (payload.model_number || 'unknown'),
    'Customer reports: ' + (payload.problem_summary || '(none)'),
  ].join('\n');

  const resp = await claude.callClaude({
    system: DIAGNOSTIC_PROMPT,
    messages: [{ role: 'user', content: userMessage }],
    model: config.claudeModel,
  });
  const briefText = (claude.textFromResponse ? claude.textFromResponse(resp) : '').trim();

  await xano.emitSignal({
    signal_type: 'DIAGNOSTIC_BRIEF',
    signal_strength: 60,
    payload: {
      job_id: jobId,
      appliance_type: APPLIANCE,
      brand: payload.brand || null,
      model_number: payload.model_number || null,
      problem_summary: payload.problem_summary || null,
      brief_text: briefText,
      generated_by: AGENT_ID,
      generated_at_ms: Date.now(),
    },
  });

  const meta = {
    job_id: jobId,
    appliance: APPLIANCE,
    agent_id: AGENT_ID,
    brief_chars: briefText.length,
    outcome: 'diagnostic_brief_emitted',
  };
  await xano.markSignalProcessed(signal.id, 'diagnostic_brief_emitted', meta);
  log('diagnostic_brief_emitted', meta);

  return {
    success: true,
    action: 'diagnostic_brief_emitted',
    job_id: jobId,
    agent_id: AGENT_ID,
  };
}
