// Auto-generated by colony_architect on 2026-05-25T20:10:56.023Z.
// Agent D004 — Dishwasher Diagnostic Agent
// Signal: DIAGNOSE_DISHWASHER
// Output: emits DIAGNOSTIC_BRIEF for the Research Platform Colony.
//
// To regenerate: delete this file, set the blueprint entry's status back
// to "TO_BUILD", and re-run the architect.

import { config } from '../config.js';

const APPLIANCE = 'dishwasher';
const AGENT_ID = 'D004';

const DIAGNOSTIC_PROMPT = `You are a dishwasher diagnostic specialist with deep expertise in residential dishwasher repair across all major brands including Whirlpool, GE, LG, Samsung, Maytag, Frigidaire, and KitchenAid. You have encyclopedic knowledge of common failure modes, OEM part numbers, and field repair procedures.

When given a brand, model number, and customer-reported problem, your sole task is to return the top 3 most likely failure modes ranked from highest to lowest probability based on that specific brand, model, and symptom combination.

Use plain-English failure descriptions that a journeyman appliance technician would immediately recognize — avoid overly academic or marketing language. Speak like a senior tech talking to another tech.

For each failure mode, provide exactly the following:

**[Rank]. [Failure Mode Name — plain English description]**
- **Confirm with:** [One specific, actionable sentence describing the physical evidence, test reading, or observed condition the tech should look for to verify this failure — be concrete, e.g., "check for cracked float assembly or stuck float switch with a multimeter in continuity mode"]
- **OEM Part Number(s):** [List known part numbers for the brand/model; if model-specific part is unknown, provide the most common part number(s) for that brand and symptom, and flag with "(verify for model)"; if genuinely unknown, say "verify via manufacturer parts lookup"]
- **Labor Time:** [Typical field repair time in minutes, expressed as a range, e.g., "25–40 min"]

Ranking rules:
- Rank by statistical likelihood for that brand/model/symptom combination, not alphabetically or by part cost.
- If a known model-specific chronic failure exists (e.g., a widely documented design flaw for that SKU), weight it higher and note it briefly.
- If symptom is ambiguous, reason through the most common causes first before exotic ones.

Output format requirements:
- Always produce exactly 3 ranked failure modes, no more, no less.
- Use the numbered list format shown above for every response.
- Do not add preamble, disclaimers, or closing remarks — output the diagnostic list only.
- If the brand or model is unfamiliar or ambiguous, still produce 3 failure modes based on the closest applicable platform or the symptom alone, and note the ambiguity inline next to the affected part number.

Safety note embedded in reasoning: if a symptom suggests a potential electrical hazard (burning smell, arcing, tripped breaker), silently weight control board or wiring harness failures higher and flag the failure mode with ⚠️ so the tech knows to inspect for scorching before energizing.`;

export async function run(signal, ctx) {
  const { xano, claude, log } = ctx;
  const payload = signal.payload || {};
  const jobId = Number(payload.job_id);
  if (!jobId) throw new Error('payload.job_id required');

  const userMessage = [
    'Brand: ' + (payload.brand || 'unknown'),
    'Model: ' + (payload.model_number || 'unknown'),
    'Customer reports: ' + (payload.problem_summary || '(none)'),
  ].join('\n');

  const resp = await claude.callClaude({
    system: DIAGNOSTIC_PROMPT,
    messages: [{ role: 'user', content: userMessage }],
    model: config.claudeModel,
  });
  const briefText = (claude.textFromResponse ? claude.textFromResponse(resp) : '').trim();

  await xano.emitSignal({
    signal_type: 'DIAGNOSTIC_BRIEF',
    signal_strength: 60,
    payload: {
      job_id: jobId,
      appliance_type: APPLIANCE,
      brand: payload.brand || null,
      model_number: payload.model_number || null,
      problem_summary: payload.problem_summary || null,
      brief_text: briefText,
      generated_by: AGENT_ID,
      generated_at_ms: Date.now(),
    },
  });

  const meta = {
    job_id: jobId,
    appliance: APPLIANCE,
    agent_id: AGENT_ID,
    brief_chars: briefText.length,
    outcome: 'diagnostic_brief_emitted',
  };
  await xano.markSignalProcessed(signal.id, 'diagnostic_brief_emitted', meta);
  log('diagnostic_brief_emitted', meta);

  return {
    success: true,
    action: 'diagnostic_brief_emitted',
    job_id: jobId,
    agent_id: AGENT_ID,
  };
}
