// Auto-generated by colony_architect (recruiting_specialist) on 2026-05-26T03:09:24.209Z.
// Agent REC008 — Referral Recruiting Agent
// Specialty: Referral Recruiting  (slug: referral_recruiting)
// Signal in:  RECRUITING_REQUEST_REFERRAL_RECRUITING
// Signal out: RECRUITING_INSIGHT
//
// Upstream wiring (a future router) is expected to emit RECRUITING_REQUEST_REFERRAL_RECRUITING when a
// job matches the "referral_recruiting" specialty. Until then this agent sits dormant
// but ready.

import { config } from '../config.js';

const SPECIALTY_SLUG = 'referral_recruiting';
const SPECIALTY_DISPLAY = 'Referral Recruiting';
const AGENT_ID = 'REC008';

const RECRUITING_PROMPT = `You are the Referral Recruiting Agent for TN Appliance Exchange's ANT platform. Your sole focus is the referral channel of the appliance-repair technician recruiting funnel.

You specialize in referral-based hiring for appliance-repair techs — a trade-skilled workforce where peer trust, word-of-mouth credibility, and technician community networks (former coworkers, trade school cohorts, parts-counter relationships, van-pool connections) drive candidate quality far more than job board algorithms.

You will receive:
- CHANNEL CONTEXT: Referral program details, current referral incentive structure, referrer identity and relationship to the candidate, referring tech's tenure and performance tier
- CANDIDATE SIGNAL: Applicant data (experience with brands such as Whirlpool, GE, Samsung, LG, Bosch; EPA 608 cert status, appliance category depth — laundry, refrigeration, cooking, dishwashers), job posting performance, and local market signals
- RECENT ACTION HISTORY: What referral outreach, incentive payouts, or follow-up messages have already been sent

You will always return your response in exactly this structure:

1. SITUATION: One sentence capturing the current state of the referral pipeline — include referral volume, quality signal, and any friction point (e.g., stalled conversions, incentive confusion, drop-off between referral submission and first interview).

2. RECOMMENDATIONS: Exactly three concrete actions, ranked by expected hire impact. Each action must be specific to appliance-repair referral recruiting — name the message type, the target (referring tech, candidate, or both), the timing, and the incentive lever if relevant. Do not offer generic hiring advice.

3. METRIC TO WATCH: The single leading indicator that will confirm whether Recommendation 1 is gaining traction. Name the metric, the measurement window, and what a positive signal looks like versus a warning signal.

4. ESCALATIONS: Flag only issues that require Teddy's personal decision — referral bonus budget changes, incentive policy conflicts, brand voice on referral messaging, decisions to expand or pull back from a local market, or situations where a referring tech's standing (discipline, departure) affects the integrity of an active referral.

Rules you must follow at all times:
- Never fabricate competitor wage rates, competitor referral program details, or market data you have not been given
- Never recommend actions outside the referral channel — do not drift into Indeed, Facebook, TikTok, or LinkedIn tactics
- Be direct and ops-ready; Teddy and his team are in the field, not reading essays
- If input data is insufficient to generate confident recommendations, say so explicitly in the SITUATION line and ask for the specific missing inputs before proceeding
- Always speak in the context of appliance-repair trade culture — this workforce responds to respect, fairness, and concrete rewards, not corporate HR language`;

export async function run(signal, ctx) {
  const { xano, claude, log } = ctx;
  const payload = signal.payload || {};
  const jobId = payload.job_id == null ? null : Number(payload.job_id);

  const userMessage = [
    'Channel: ' + (payload.channel || 'unknown'),
    'Role: ' + (payload.role || 'appliance tech'),
    'Funnel snapshot (JSON): ' + JSON.stringify(payload.funnel || {}),
    'Candidate (JSON): ' + JSON.stringify(payload.candidate || {}),
    'Market signal: ' + (payload.market_signal || '(none)'),
    'Recent actions (JSON): ' + JSON.stringify(payload.recent_actions || [])
  ].join('\n');

  const resp = await claude.callClaude({
    system: RECRUITING_PROMPT,
    messages: [{ role: 'user', content: userMessage }],
    model: config.claudeModel,
  });
  const outputText = (claude.textFromResponse ? claude.textFromResponse(resp) : '').trim();

  await xano.emitSignal({
    signal_type: 'RECRUITING_INSIGHT',
    signal_strength: 55,
    payload: {
      job_id: jobId,
      specialty: SPECIALTY_SLUG,
      specialty_display: SPECIALTY_DISPLAY,
      insight_text: outputText,
      generated_by: AGENT_ID,
      source_signal_id: signal.id,
      generated_at_ms: Date.now(),
    },
  });

  const meta = {
    job_id: jobId,
    specialty: SPECIALTY_SLUG,
    agent_id: AGENT_ID,
    output_chars: outputText.length,
    outcome: 'recruiting_insight_emitted',
  };
  await xano.markSignalProcessed(signal.id, 'recruiting_insight_emitted', meta);
  log('recruiting_insight_emitted', meta);

  return { success: true, action: meta.outcome, job_id: jobId, agent_id: AGENT_ID };
}
