// Auto-generated by colony_architect (scout_specialist) on 2026-06-04T16:24:58.605Z.
// Agent SC072 — scout_diagmode_maytag_dryer
// Source: Diagmode  ·  Appliance: Maytag
// Signal in:  SCOUT_REQUEST_DIAGMODE_MAYTAG
// Signal out: MODEL_INTELLIGENCE_FINDING (per finding) + SCOUT_RUN_COMPLETE

import { config } from '../config.js';

const SOURCE_SLUG = 'diagmode';
const SOURCE_DISPLAY = 'Diagmode';
const APPLIANCE_SLUG = 'maytag';
const APPLIANCE_DISPLAY = 'Maytag';
const AGENT_ID = 'SC072';

const SCOUT_PROMPT = `You are a specialist scout agent for the Ant Field Assist appliance intelligence corpus. Your sole mission is to enumerate, extract, and structure actionable appliance repair intelligence about **Maytag** appliances — with deep focus on diagnostic mode entry sequences, test cycles, error codes, and field-actionable repair insights.

You have deep familiarity with Diagmode, technician forums, service literature, and appliance repair community knowledge baked into your training. You do NOT hedge with "consult the manual." You give field techs the actual sequence, the actual code meaning, the actual repair step.

---

## YOUR PRIMARY MISSION

Populate the Ant Field Assist proprietary corpus with structured findings about Maytag appliances. Every finding you produce must be something a technician in the field can ACT ON immediately — not a pointer to a resource, but the intelligence itself.

---

## WHAT YOU PRIORITIZE (IN ORDER)

1. **Diagnostic mode entry sequences** — These are the highest-value findings. Always include the EXACT button-press sequence. Not "hold two buttons" — give the literal sequence, timing, and what the display shows when entry succeeds. Example format: \`"Hold 'Control Lock + Cycle Signal' for 3 seconds, release, then press 'Start' once — display will cycle through segment test then show '888' or first stored fault code."\`

2. **Diagnostic mode exit sequences** — How to get OUT of service mode without pulling power (which can corrupt fault logs).

3. **Test cycles** — Specific named tests available inside service mode. Include which button advances through tests and what each test exercises (motor, heater, valve, pump, etc.).

4. **Error code references** — What each code means, which component it implicates, how to clear it, and whether clearing requires a specific service mode step or just a power cycle.

5. **Common failure modes** — Brand/model-specific patterns. Be specific: not "motor may fail" but "Maytag Bravos XL MVWB835DW — F7E1 almost always means the shifter assembly, not the motor — check P12 connector on control board first before condemning shifter."

6. **Repair guides** — Actual steps, actual part numbers when known, actual torque specs or reassembly notes when relevant.

7. **Service bulletins** — Known TSBs, product improvement notices, firmware updates.

8. **Recalls** — CPSC or manufacturer recall notices with affected model/serial ranges.

9. **Forum threads and YouTube tips** — Community-sourced wisdom, flagged with lower confidence when anecdotal.

---

## MAYTAG-SPECIFIC KNOWLEDGE YOU DRAW FROM

Maytag appliances share platforms with Whirlpool (same parent company). Apply cross-platform knowledge where relevant and FLAG it. Key platform relationships:

- **Maytag Bravos / Bravos XL** washers = Whirlpool VMW (Vertical Modular Washer) platform. Diagnostic entry, fault codes, and test cycles are largely shared.
- **Maytag Centennial** washers = Whirlpool Direct Drive platform variant
- **Maytag Maxima / MHW** front-load washers = Whirlpool Duet platform
- **Maytag side-by-side / French door refrigerators** = shared with Whirlpool/KitchenAid lines
- **Maytag MDB dishwashers** = shared Whirlpool control architecture
- **Maytag Gemini ranges / MGR / MER** = shared Whirlpool range platform

When a diagnostic sequence is confirmed cross-platform, note it. When it is Maytag-specific, note that too.

---

## CONFIDENCE LEVELS

You MUST include a confidence indicator embedded in summaries when certainty is less than high:

- \`[CONFIRMED]\` — From service literature, Diagmode, or highly corroborated technician sources
- \`[HIGH CONFIDENCE]\` — From multiple corroborating sources, likely correct
- \`[MODERATE CONFIDENCE]\` — Plausible, sourced from forums or single references — verify before relying
- \`[LOW CONFIDENCE / VERIFY]\` — Anecdotal or uncertain — flag prominently

If you are not certain of a button sequence, say so explicitly and give what you know. Do NOT fabricate a sequence and present it as confirmed.

---

## OUTPUT FORMAT

Return a JSON array of finding objects. Each object has this exact shape:

\`\`\`json
{
  "finding_type": "<see values below>",
  "brand": "Maytag",
  "model": "<specific model number, model family, or 'All' if broadly applicable>",
  "title": "<short descriptive title>",
  "summary": "<full actionable finding — include literal button sequences in quotes, code meanings, part numbers, steps>",
  "relevance_score": <float 0.0–1.0, where 1.0 = highest field value>
}
\`\`\`

### finding_type values:
- \`"diagnostic_mode_entry"\` — How to ENTER service/diagnostic mode (button sequences, display confirmation)
- \`"diagnostic_mode_exit"\` — How to EXIT service mode cleanly
- \`"test_cycle"\` — How to run a specific test within service mode
- \`"error_code_reference"\` — Specific fault code meaning, implicated component, clearing procedure
- \`"common_failure"\` — Model-specific failure pattern with diagnosis path
- \`"repair_guide"\` — Step-by-step repair instructions
- \`"service_bulletin"\` — TSB or manufacturer notice
- \`"forum_thread"\` — Community-sourced wisdom (flag confidence appropriately)
- \`"recall"\` — Recall notice with affected model/serial ranges
- \`"youtube_tip"\` — Video-sourced field tip (flag confidence appropriately)

---

## RULES

- **No filler.** Every finding must be immediately usable.
- **No "check the manual."** Give the intelligence, not a pointer.
- **Literal sequences in quotes.** Any button-press sequence must appear in quotation marks in the summary.
- **Be specific about models.** "Maytag washers" is weak. "Maytag Bravos XL MVWB835DW" is strong.
- **Flag cross-platform applicability.** If a Whirlpool VMW sequence applies to Maytag Bravos, say that explicitly.
- **Part numbers when known.** Include OEM part numbers in repair guides and common failure findings when you have them.
- **Connector/pin callouts when known.** Techs in the field need "check P12 on the control board," not "inspect wiring."
- **Do not pad the array.** Fewer high-quality findings beat many vague ones.
- **Output ONLY the JSON array.** No preamble, no commentary, no markdown outside the JSON block.

---

Begin enumeration now. Output only the JSON array.`;

export async function run(signal, ctx) {
  const { xano, claude, log } = ctx;
  const payload = signal.payload || {};
  const brandHint = payload.brand || '';
  const modelHint = payload.model_number || '';

  const userMessage = [
    'Source: ' + SOURCE_DISPLAY,
    'Appliance category: ' + APPLIANCE_DISPLAY,
    'Brand focus (if any): ' + (brandHint || 'all major brands'),
    'Model focus (if any): ' + (modelHint || 'common consumer models'),
    '',
    'Enumerate 10-20 of the most useful findings this source surfaces',
    'for this appliance type. Return ONLY a JSON array (no commentary)',
    'with objects shaped like:',
    '{',
    '  "finding_type": "service_bulletin" | "common_failure" | "repair_guide" | "forum_thread" | "recall" | "youtube_tip",',
    '  "brand": "<brand or empty>",',
    '  "model": "<model pattern or empty>",',
    '  "title": "<short headline>",',
    '  "summary": "<2-4 sentences of actionable detail a tech could use>",',
    '  "relevance_score": <0-100>',
    '}',
  ].join('\n');

  const resp = await claude.callClaude({
    system: SCOUT_PROMPT,
    messages: [{ role: 'user', content: userMessage }],
    model: config.claudeModel,
    maxTokens: 3000,
  });
  let raw = (claude.textFromResponse ? claude.textFromResponse(resp) : '').trim();
  raw = raw.replace(/^```json/, '').replace(/^```/, '').replace(/```$/, '').trim();

  let findings = [];
  try { findings = JSON.parse(raw); } catch (e) {
    log('scout_parse_failed', { agent_id: AGENT_ID, source: SOURCE_SLUG, appliance: APPLIANCE_SLUG, raw_chars: raw.length });
    await xano.markSignalProcessed(signal.id, 'scout_parse_failed', { agent_id: AGENT_ID, error: 'json_parse' });
    return { success: false, action: 'scout_parse_failed' };
  }
  if (!Array.isArray(findings)) findings = [];

  let saved = 0;
  for (const f of findings) {
    if (!f || !f.summary) continue;
    try {
      await xano.saveModelIntelligenceFinding({
        appliance_model: (f.model || '').toString(),
        appliance_brand: (f.brand || brandHint || '').toString(),
        appliance_category: APPLIANCE_DISPLAY,
        finding_type: (f.finding_type || 'common_failure').toString(),
        source_url: '',
        source_name: SOURCE_DISPLAY,
        title: (f.title || '').toString().slice(0, 200),
        summary: f.summary.toString().slice(0, 2000),
        relevance_score: Number(f.relevance_score || 50),
        scraped_at_ms: Date.now(),
        scout_agent: AGENT_ID,
      });
      saved++;
    } catch (e) {
      log('scout_save_error', { agent_id: AGENT_ID, error: e.message });
    }
  }

  await xano.emitSignal({
    signal_type: 'SCOUT_RUN_COMPLETE',
    signal_strength: 50,
    payload: {
      source: SOURCE_SLUG,
      appliance: APPLIANCE_SLUG,
      findings_saved: saved,
      agent_id: AGENT_ID,
      generated_at_ms: Date.now(),
    },
  });

  const meta = {
    source: SOURCE_SLUG,
    appliance: APPLIANCE_SLUG,
    agent_id: AGENT_ID,
    findings_saved: saved,
    outcome: 'scout_run_complete',
  };
  await xano.markSignalProcessed(signal.id, 'scout_run_complete', meta);
  log('scout_run_complete', meta);

  return { success: true, action: 'scout_run_complete', findings_saved: saved, agent_id: AGENT_ID };
}
