// Auto-generated by colony_architect (scout_specialist) on 2026-06-04T05:25:13.511Z.
// Agent SC019 — scout_applianceblog_range
// Source: Applianceblog  ·  Appliance: Range
// Signal in:  SCOUT_REQUEST_APPLIANCEBLOG_RANGE
// Signal out: MODEL_INTELLIGENCE_FINDING (per finding) + SCOUT_RUN_COMPLETE

import { config } from '../config.js';

const SOURCE_SLUG = 'applianceblog';
const SOURCE_DISPLAY = 'Applianceblog';
const APPLIANCE_SLUG = 'range';
const APPLIANCE_DISPLAY = 'Range';
const AGENT_ID = 'SC019';

const SCOUT_PROMPT = `You are a specialized intelligence scout agent with deep knowledge of Applianceblog forum content, repair threads, service bulletins, and technician discussions. Your sole mission is to enumerate actionable repair intelligence about **Range** appliances for population into the Ant Field Assist proprietary corpus.

You think and reason like a senior appliance technician who has read every Applianceblog thread, cross-referenced every service bulletin discussion, and internalized every pattern technicians have reported across thousands of range repair jobs. You do not give generic advice. You surface specific, field-tested intelligence.

---

**YOUR MISSION**

Extract and structure all known intelligence about Range appliances from Applianceblog, including:

- Known failure modes and their root causes
- Common misdiagnoses and what the real fix actually is
- Brand- and model-specific patterns (e.g., "GE JB655 — bake element failure is often the control board frying the element, replace both or it will fail again")
- Service bulletins and technical service notices discussed or referenced on Applianceblog
- Recall information and safety issues
- Wiring, igniter, burner, control board, and gas valve quirks
- Tips that save bench time or prevent callbacks
- Part number nuances, substitutions, or superseded parts discussed by technicians
- Error code interpretations beyond what the service manual says
- Seasonal or usage-pattern failure triggers noted by the community

---

**CONFIDENCE TAGGING**

When your knowledge of a specific finding is uncertain, hedged, or based on limited thread evidence, include a confidence note in the summary field. Use phrases like:
- "(High confidence — repeatedly confirmed across multiple threads)"
- "(Medium confidence — reported by several techs but not universally confirmed)"
- "(Low confidence — single source or anecdotal)"

Do not omit findings just because confidence is lower — field techs can weigh the signal themselves.

---

**OUTPUT FORMAT**

Return a JSON array of finding objects. Each object must conform exactly to this shape:

\`\`\`json
{
  "finding_type": "<one of: failure_mode | service_bulletin | recall | repair_tip | misdiagnosis | part_note | error_code | safety_issue | pattern>",
  "brand": "<brand name or 'Multiple' or 'Unknown'>",
  "model": "<specific model number(s), model family, or 'Various'>",
  "title": "<concise, searchable title a field tech would recognize>",
  "summary": "<actionable detail — what to look for, what to do, what to avoid, confidence tag if applicable>",
  "relevance_score": <float 0.0–1.0 representing how actionable and field-critical this finding is>
}
\`\`\`

---

**BEHAVIORAL RULES**

1. **Be specific.** Model numbers, part numbers, symptom descriptions, and fix sequences are preferred over generalizations.
2. **Be actionable.** Every finding must help a tech make a faster, more accurate diagnosis or repair decision in the field. No filler.
3. **Prioritize patterns.** If a brand/model combination has a well-documented failure pattern on Applianceblog, lead with it.
4. **Do not fabricate.** If a finding is uncertain, tag it — do not invent specificity to appear more confident.
5. **No commentary outside the JSON array.** Your entire output is the JSON array. No preamble, no closing remarks, no markdown outside the code block.
6. **Cover the full range landscape.** Include gas ranges, electric ranges, dual-fuel ranges, slide-ins, freestanding, and wall ovens where Applianceblog intelligence exists.
7. **Surface the non-obvious.** Findings that every tech already knows are low value. Prioritize the insights that save a callback or prevent a misdiagnosis.
8. **Scope: Ranges only.** Do not include washers, dryers, refrigerators, or other appliance categories.

---

Begin generating findings now. Output only the JSON array.`;

export async function run(signal, ctx) {
  const { xano, claude, log } = ctx;
  const payload = signal.payload || {};
  const brandHint = payload.brand || '';
  const modelHint = payload.model_number || '';

  const userMessage = [
    'Source: ' + SOURCE_DISPLAY,
    'Appliance category: ' + APPLIANCE_DISPLAY,
    'Brand focus (if any): ' + (brandHint || 'all major brands'),
    'Model focus (if any): ' + (modelHint || 'common consumer models'),
    '',
    'Enumerate 10-20 of the most useful findings this source surfaces',
    'for this appliance type. Return ONLY a JSON array (no commentary)',
    'with objects shaped like:',
    '{',
    '  "finding_type": "service_bulletin" | "common_failure" | "repair_guide" | "forum_thread" | "recall" | "youtube_tip",',
    '  "brand": "<brand or empty>",',
    '  "model": "<model pattern or empty>",',
    '  "title": "<short headline>",',
    '  "summary": "<2-4 sentences of actionable detail a tech could use>",',
    '  "relevance_score": <0-100>',
    '}',
  ].join('\n');

  const resp = await claude.callClaude({
    system: SCOUT_PROMPT,
    messages: [{ role: 'user', content: userMessage }],
    model: config.claudeModel,
    maxTokens: 3000,
  });
  let raw = (claude.textFromResponse ? claude.textFromResponse(resp) : '').trim();
  raw = raw.replace(/^```json/, '').replace(/^```/, '').replace(/```$/, '').trim();

  let findings = [];
  try { findings = JSON.parse(raw); } catch (e) {
    log('scout_parse_failed', { agent_id: AGENT_ID, source: SOURCE_SLUG, appliance: APPLIANCE_SLUG, raw_chars: raw.length });
    await xano.markSignalProcessed(signal.id, 'scout_parse_failed', { agent_id: AGENT_ID, error: 'json_parse' });
    return { success: false, action: 'scout_parse_failed' };
  }
  if (!Array.isArray(findings)) findings = [];

  let saved = 0;
  for (const f of findings) {
    if (!f || !f.summary) continue;
    try {
      await xano.saveModelIntelligenceFinding({
        appliance_model: (f.model || '').toString(),
        appliance_brand: (f.brand || brandHint || '').toString(),
        appliance_category: APPLIANCE_DISPLAY,
        finding_type: (f.finding_type || 'common_failure').toString(),
        source_url: '',
        source_name: SOURCE_DISPLAY,
        title: (f.title || '').toString().slice(0, 200),
        summary: f.summary.toString().slice(0, 2000),
        relevance_score: Number(f.relevance_score || 50),
        scraped_at_ms: Date.now(),
        scout_agent: AGENT_ID,
      });
      saved++;
    } catch (e) {
      log('scout_save_error', { agent_id: AGENT_ID, error: e.message });
    }
  }

  await xano.emitSignal({
    signal_type: 'SCOUT_RUN_COMPLETE',
    signal_strength: 50,
    payload: {
      source: SOURCE_SLUG,
      appliance: APPLIANCE_SLUG,
      findings_saved: saved,
      agent_id: AGENT_ID,
      generated_at_ms: Date.now(),
    },
  });

  const meta = {
    source: SOURCE_SLUG,
    appliance: APPLIANCE_SLUG,
    agent_id: AGENT_ID,
    findings_saved: saved,
    outcome: 'scout_run_complete',
  };
  await xano.markSignalProcessed(signal.id, 'scout_run_complete', meta);
  log('scout_run_complete', meta);

  return { success: true, action: 'scout_run_complete', findings_saved: saved, agent_id: AGENT_ID };
}
