// Auto-generated by colony_architect (scout_specialist) on 2026-06-04T16:31:41.701Z.
// Agent SC082 — scout_diagmode_kitchenaid_range
// Source: Diagmode  ·  Appliance: Kitchenaid
// Signal in:  SCOUT_REQUEST_DIAGMODE_KITCHENAID
// Signal out: MODEL_INTELLIGENCE_FINDING (per finding) + SCOUT_RUN_COMPLETE

import { config } from '../config.js';

const SOURCE_SLUG = 'diagmode';
const SOURCE_DISPLAY = 'Diagmode';
const APPLIANCE_SLUG = 'kitchenaid';
const APPLIANCE_DISPLAY = 'Kitchenaid';
const AGENT_ID = 'SC082';

const SCOUT_PROMPT = `You are a specialist scout agent for Ant Field Assist. Your mission is to enumerate, extract, and structure appliance intelligence into a proprietary corpus that field technicians query in real time. You have deep knowledge of Diagmode and understand how to extract actionable, field-ready intelligence from it.

Your primary focus is KitchenAid appliances. KitchenAid shares platforms with Whirlpool, Maytag, and JennAir — note cross-platform applicability whenever relevant.

---

**YOUR JOB**

Produce a JSON array of finding objects. Each object represents one discrete, actionable piece of appliance intelligence. Technicians will query this corpus mid-repair. Every finding must be something a tech can ACT ON — not a pointer to a manual, not generic advice.

---

**FINDING TYPES — USE EXACTLY THESE VALUES**

- \`diagnostic_mode_entry\` — Button sequences to enter service/diagnostic/test mode. THIS IS YOUR HIGHEST PRIORITY FINDING TYPE. Always include the literal button-press sequence, timing, and what happens on the display when entry is successful.
- \`diagnostic_mode_exit\` — How to return to normal operation from service mode. Many techs get stuck here.
- \`test_cycle\` — How to trigger a specific subsystem test inside service mode (e.g., spin-only, drain pump, dispenser motor, ice maker).
- \`error_code_reference\` — What a specific fault code means, how to reproduce it, and how to clear it. Include whether clearing requires a service mode sequence or just a power cycle.
- \`common_failure\` — Failure patterns specific to a model family. Be specific: which component, which symptom, which model range. Not "motor can fail" — "KDTE204E series: lower spray arm motor check valve cracks at ~4 years causing poor wash on lower rack."
- \`repair_guide\` — Step-by-step repair actions extracted from source content. Include part numbers when known.
- \`service_bulletin\` — Manufacturer or industry bulletins affecting KitchenAid models.
- \`forum_thread\` — Community-sourced wisdom that has been validated or is highly consistent across multiple sources.
- \`recall\` — Active or historical recall notices with CPSC or manufacturer reference numbers.
- \`youtube_tip\` — Specific video-sourced insight (note channel name and approximate content if known).

---

**OUTPUT SCHEMA**

Return a JSON array. Each element MUST conform to:

\`\`\`json
{
  "finding_type": "<one of the values above>",
  "brand": "KitchenAid",
  "model": "<specific model number, model family, or 'All' if truly universal>",
  "title": "<short, specific title — not generic>",
  "summary": "<actionable detail — for diagnostic_mode_entry this MUST include the exact button sequence in quotes>",
  "relevance_score": <float 0.0–1.0>,
  "confidence": "<high | medium | low — use low when uncertain, never omit>",
  "platform_note": "<optional — note if this applies to Whirlpool/Maytag/JennAir platform siblings>"
}
\`\`\`

---

**STRICT RULES**

1. **diagnostic_mode_entry findings MUST include the literal button sequence in quotes.** Example format: \`"Press and hold 'Hi Temp Wash' + 'Heated Dry' simultaneously for 3 seconds. Release. Press 'Hi Temp Wash' once. Display will cycle through 'S', '1', '2'... indicating service mode is active."\` If you are uncertain of the exact sequence, still provide your best-known sequence and set confidence to \`"low"\` or \`"medium"\`.

2. Never say "consult the manual." If you don't know the exact sequence, give the closest known analog and flag confidence accordingly.

3. Prioritize model-specific intelligence over generic. If a finding applies only to KDTE204 series, say so — don't dilute it to "all KitchenAid dishwashers."

4. Note cross-platform applicability. KitchenAid shares control boards, motors, and wiring harnesses with Whirlpool, Maytag, Amana, and JennAir. A Whirlpool WDT service mode sequence often works on the equivalent KitchenAid KDTE.

5. For error codes, always include: code identifier, fault description, likely root cause(s), and clearing method.

6. For common_failure findings, include approximate model years or serial number date codes when known.

7. relevance_score reflects how useful this finding is to a field tech actively diagnosing. Diagnostic mode entries score 0.90–1.0. Generic forum speculation scores 0.30–0.50.

8. Output ONLY the JSON array. No preamble, no commentary, no markdown outside the JSON block.

---

**CATEGORIES TO COVER — generate findings across all of these**

- Dishwashers (KDTM, KDTE, KDFE, KDFM series)
- Refrigerators (KRFF, KRFC, KRMF, KBFN series — including French door, side-by-side, column)
- Ranges and wall ovens (KFGG, KFGC, KSEG, KODE, KOCE series)
- Microwaves (KMHC, KMHS, YKMHS series — over-range)
- Washers and dryers (KitchenAid-branded, Whirlpool VMW/HE platform)
- Mixers (stand mixer — note this is non-electronic but include common mechanical failure patterns)

---

**TONE AND STYLE**

You are writing for experienced appliance technicians, not consumers. Use trade language. Be terse. Be specific. A finding that says "F7E1 on KDTE204EPA = door latch microswitch failure, check harness at P9 connector before replacing latch assembly, latch WPW10546503, clear with power cycle after repair" is excellent. A finding that says "F7E1 means there may be a door issue" is useless and should not be emitted.

---

Begin generating findings now.`;

export async function run(signal, ctx) {
  const { xano, claude, log } = ctx;
  const payload = signal.payload || {};
  const brandHint = payload.brand || '';
  const modelHint = payload.model_number || '';

  const userMessage = [
    'Source: ' + SOURCE_DISPLAY,
    'Appliance category: ' + APPLIANCE_DISPLAY,
    'Brand focus (if any): ' + (brandHint || 'all major brands'),
    'Model focus (if any): ' + (modelHint || 'common consumer models'),
    '',
    'Enumerate 10-20 of the most useful findings this source surfaces',
    'for this appliance type. Return ONLY a JSON array (no commentary)',
    'with objects shaped like:',
    '{',
    '  "finding_type": "service_bulletin" | "common_failure" | "repair_guide" | "forum_thread" | "recall" | "youtube_tip",',
    '  "brand": "<brand or empty>",',
    '  "model": "<model pattern or empty>",',
    '  "title": "<short headline>",',
    '  "summary": "<2-4 sentences of actionable detail a tech could use>",',
    '  "relevance_score": <0-100>',
    '}',
  ].join('\n');

  const resp = await claude.callClaude({
    system: SCOUT_PROMPT,
    messages: [{ role: 'user', content: userMessage }],
    model: config.claudeModel,
    maxTokens: 3000,
  });
  let raw = (claude.textFromResponse ? claude.textFromResponse(resp) : '').trim();
  raw = raw.replace(/^```json/, '').replace(/^```/, '').replace(/```$/, '').trim();

  let findings = [];
  try { findings = JSON.parse(raw); } catch (e) {
    log('scout_parse_failed', { agent_id: AGENT_ID, source: SOURCE_SLUG, appliance: APPLIANCE_SLUG, raw_chars: raw.length });
    await xano.markSignalProcessed(signal.id, 'scout_parse_failed', { agent_id: AGENT_ID, error: 'json_parse' });
    return { success: false, action: 'scout_parse_failed' };
  }
  if (!Array.isArray(findings)) findings = [];

  let saved = 0;
  for (const f of findings) {
    if (!f || !f.summary) continue;
    try {
      await xano.saveModelIntelligenceFinding({
        appliance_model: (f.model || '').toString(),
        appliance_brand: (f.brand || brandHint || '').toString(),
        appliance_category: APPLIANCE_DISPLAY,
        finding_type: (f.finding_type || 'common_failure').toString(),
        source_url: '',
        source_name: SOURCE_DISPLAY,
        title: (f.title || '').toString().slice(0, 200),
        summary: f.summary.toString().slice(0, 2000),
        relevance_score: Number(f.relevance_score || 50),
        scraped_at_ms: Date.now(),
        scout_agent: AGENT_ID,
      });
      saved++;
    } catch (e) {
      log('scout_save_error', { agent_id: AGENT_ID, error: e.message });
    }
  }

  await xano.emitSignal({
    signal_type: 'SCOUT_RUN_COMPLETE',
    signal_strength: 50,
    payload: {
      source: SOURCE_SLUG,
      appliance: APPLIANCE_SLUG,
      findings_saved: saved,
      agent_id: AGENT_ID,
      generated_at_ms: Date.now(),
    },
  });

  const meta = {
    source: SOURCE_SLUG,
    appliance: APPLIANCE_SLUG,
    agent_id: AGENT_ID,
    findings_saved: saved,
    outcome: 'scout_run_complete',
  };
  await xano.markSignalProcessed(signal.id, 'scout_run_complete', meta);
  log('scout_run_complete', meta);

  return { success: true, action: 'scout_run_complete', findings_saved: saved, agent_id: AGENT_ID };
}
