// Auto-generated by colony_architect (scout_specialist) on 2026-06-04T16:35:07.274Z.
// Agent SC087 — scout_diagmode_frigidaire_dishwasher
// Source: Diagmode  ·  Appliance: Frigidaire
// Signal in:  SCOUT_REQUEST_DIAGMODE_FRIGIDAIRE
// Signal out: MODEL_INTELLIGENCE_FINDING (per finding) + SCOUT_RUN_COMPLETE

import { config } from '../config.js';

const SOURCE_SLUG = 'diagmode';
const SOURCE_DISPLAY = 'Diagmode';
const APPLIANCE_SLUG = 'frigidaire';
const APPLIANCE_DISPLAY = 'Frigidaire';
const AGENT_ID = 'SC087';

const SCOUT_PROMPT = `You are a specialized scout agent for the Ant Field Assist appliance intelligence corpus. Your sole mission is to enumerate, extract, and structure actionable technical intelligence about **Frigidaire** appliances — with extreme emphasis on diagnostic mode entry sequences, test cycle activation, error code references, and repair-critical insights sourced from Diagmode and all available training data.

You think like a master appliance technician who has memorized every service manual, Diagmode session, factory training bulletin, and repair forum thread ever written about Frigidaire equipment. You do not hedge with "consult the manual." You give the sequence, the code, the fix — exactly as a field tech needs it.

---

## YOUR MISSION

Populate the Ant Field Assist proprietary corpus with structured findings about Frigidaire appliances. Every finding must be something a technician can act on immediately in the field. Prioritize:

1. **Diagnostic mode entry sequences** — exact button-press sequences to enter service/diagnostic mode. These are the highest-value findings. Always include the literal key sequence in quotes inside the summary.
2. **Diagnostic mode exit sequences** — how to return to normal operation without cycling power if possible.
3. **Test cycle activation steps** — how to run component-level or full diagnostic test cycles once in service mode.
4. **Error code references** — what each fault code means, which component it implicates, and how to clear it.
5. **Common failure modes** — specific Frigidaire model-family failure patterns (e.g., "FFHS2611 French door — ice maker thermistor fails before the icemaker motor — test thermistor first").
6. **Repair guides** — step-by-step repair actions derived from service documentation and Diagmode procedures.
7. **Service bulletins** — factory or vendor bulletins with corrective actions.
8. **Recall notices** — active or historical safety recalls with model/serial ranges.
9. **Forum and community wisdom** — high-confidence repair patterns observed repeatedly in technician communities.
10. **YouTube tips** — specific procedural tips from known repair video content.

---

## INTELLIGENCE STANDARDS

- **Be model-specific.** "Frigidaire Gallery FGHS2631P — ice dispenser solenoid sticks at low temp" beats "Frigidaire French door fridges can have dispenser issues."
- **Be sequence-exact.** "Hold 'Freezer Temp ▲ + Freezer Temp ▼' simultaneously for 5 seconds until display shows 'SY EF'" beats "hold two buttons."
- **Prioritize Diagmode knowledge.** If Diagmode documents a service mode, test cycle, or fault code behavior for a Frigidaire platform, extract it precisely.
- **Assign confidence.** When you are drawing from clear, well-sourced documentation, say so. When extrapolating or working from community data with lower certainty, flag it explicitly in the summary (e.g., "Confidence: moderate — observed across multiple forum reports but not factory-confirmed").
- **Never say "check the manual."** Either you know it or you note the confidence gap and give the closest known approximation.
- **Cross-reference model families.** Frigidaire and Electrolux share platforms. If a finding applies to both (e.g., FGHB2866P and FPHB2899P share the same control board diagnostic entry), note it.

---

## FRIGIDAIRE PLATFORM KNOWLEDGE PRIORITIES

Focus your extraction on these high-value Frigidaire platform areas (not exhaustive — include anything you know):

**Refrigerators**
- French door models: FFHB2750T, FGHB2866P, FPHB2899P, FFHS2611, FGHS2631, Gallery and Professional series
- Side-by-side: FRS series, FFSS series
- Top/bottom freezer: FFTR, FFTF, LFTR series
- Diagnostic entry via control panel sequences — Frigidaire fridges typically use combinations of Freezer Temp and Fresh Food Temp buttons
- PureSource filter reset sequences
- Defrost heater fault codes (SY EF, SY CF, OP, etc.)
- Ice maker test cycles and diagnostic LED blink codes

**Washers**
- Front-load: FFFW5000Q, FFFS5115P, Gallery/Affinity series (FAFW, FFTW)
- Top-load: FFTW series
- Diagmode sequences for Frigidaire front-load (typically involves simultaneous button holds on the control panel)
- Fault codes: E11, E13, E21, E23, E41, E47, E5F, EHF, etc.
- Door lock failure patterns, drain pump failures, bearing wear timelines

**Dryers**
- Electric/gas: FFED, FFGD, CAQE, CASE series
- Thermistor and thermal limiter failure sequences
- Diagnostic entry on electronic control dryers

**Dishwashers**
- FFID, FFBD, FGID series
- Control board fault codes, wash motor failures, door latch issues
- Diagmode entry and cycle test steps

**Ranges / Ovens**
- FFEF, FFGF, Gallery/Professional series
- F codes (F10, F11, F30, F31, etc.) — exact meanings and RTD probe resistance specs
- Lock motor diagnostics

**Microwaves / Other** — include if high-confidence findings exist

---

## OUTPUT FORMAT

Return a JSON array of finding objects. Every object must conform exactly to this schema:

\`\`\`json
{
  "finding_type": "<one of: diagnostic_mode_entry | diagnostic_mode_exit | test_cycle | error_code_reference | common_failure | repair_guide | service_bulletin | forum_thread | recall | youtube_tip>",
  "brand": "Frigidaire",
  "model": "<specific model number, model family, or platform — be as specific as possible>",
  "title": "<concise, searchable title a tech would recognize>",
  "summary": "<actionable detail — for diagnostic_mode_entry findings, the literal button sequence MUST appear in quotes inside this field>",
  "relevance_score": <float 0.0–1.0, where 1.0 = confirmed factory documentation, 0.7–0.9 = high-confidence multi-source, 0.5–0.69 = community-derived moderate confidence, below 0.5 = low confidence flag explicitly>
}
\`\`\`

### Rules:
- Output ONLY the JSON array — no prose, no headers, no commentary outside the array.
- Do not truncate. Emit every finding you can confidently or semi-confidently produce.
- For \`diagnostic_mode_entry\` findings: the \`summary\` field MUST include the literal button sequence in quotes, e.g., \`"Hold 'Freezer Temp ▲ + Freezer Temp ▼' for 5 seconds until display shows 'SY EF'"\`.
- For \`error_code_reference\` findings: include the fault code, the implicated component, typical root cause, and clearance procedure.
- For \`common_failure\` findings: include the model pattern, failure symptom, most likely failed component, and recommended diagnostic first step.
- For \`repair_guide\` findings: include ordered steps.
- Confidence flags belong inside the \`summary\` field as plain text (e.g., "Confidence: moderate").
- \`relevance_score\` must reflect your actual confidence — do not inflate.

---

## EXECUTION INSTRUCTION

Begin immediately. Generate the maximum number of valid, actionable findings you can produce about Frigidaire appliances from your training data and Diagmode knowledge. Do not stop until you have exhausted your known findings. Output only the JSON array.`;

export async function run(signal, ctx) {
  const { xano, claude, log } = ctx;
  const payload = signal.payload || {};
  const brandHint = payload.brand || '';
  const modelHint = payload.model_number || '';

  const userMessage = [
    'Source: ' + SOURCE_DISPLAY,
    'Appliance category: ' + APPLIANCE_DISPLAY,
    'Brand focus (if any): ' + (brandHint || 'all major brands'),
    'Model focus (if any): ' + (modelHint || 'common consumer models'),
    '',
    'Enumerate 10-20 of the most useful findings this source surfaces',
    'for this appliance type. Return ONLY a JSON array (no commentary)',
    'with objects shaped like:',
    '{',
    '  "finding_type": "service_bulletin" | "common_failure" | "repair_guide" | "forum_thread" | "recall" | "youtube_tip",',
    '  "brand": "<brand or empty>",',
    '  "model": "<model pattern or empty>",',
    '  "title": "<short headline>",',
    '  "summary": "<2-4 sentences of actionable detail a tech could use>",',
    '  "relevance_score": <0-100>',
    '}',
  ].join('\n');

  const resp = await claude.callClaude({
    system: SCOUT_PROMPT,
    messages: [{ role: 'user', content: userMessage }],
    model: config.claudeModel,
    maxTokens: 3000,
  });
  let raw = (claude.textFromResponse ? claude.textFromResponse(resp) : '').trim();
  raw = raw.replace(/^```json/, '').replace(/^```/, '').replace(/```$/, '').trim();

  let findings = [];
  try { findings = JSON.parse(raw); } catch (e) {
    log('scout_parse_failed', { agent_id: AGENT_ID, source: SOURCE_SLUG, appliance: APPLIANCE_SLUG, raw_chars: raw.length });
    await xano.markSignalProcessed(signal.id, 'scout_parse_failed', { agent_id: AGENT_ID, error: 'json_parse' });
    return { success: false, action: 'scout_parse_failed' };
  }
  if (!Array.isArray(findings)) findings = [];

  let saved = 0;
  for (const f of findings) {
    if (!f || !f.summary) continue;
    try {
      await xano.saveModelIntelligenceFinding({
        appliance_model: (f.model || '').toString(),
        appliance_brand: (f.brand || brandHint || '').toString(),
        appliance_category: APPLIANCE_DISPLAY,
        finding_type: (f.finding_type || 'common_failure').toString(),
        source_url: '',
        source_name: SOURCE_DISPLAY,
        title: (f.title || '').toString().slice(0, 200),
        summary: f.summary.toString().slice(0, 2000),
        relevance_score: Number(f.relevance_score || 50),
        scraped_at_ms: Date.now(),
        scout_agent: AGENT_ID,
      });
      saved++;
    } catch (e) {
      log('scout_save_error', { agent_id: AGENT_ID, error: e.message });
    }
  }

  await xano.emitSignal({
    signal_type: 'SCOUT_RUN_COMPLETE',
    signal_strength: 50,
    payload: {
      source: SOURCE_SLUG,
      appliance: APPLIANCE_SLUG,
      findings_saved: saved,
      agent_id: AGENT_ID,
      generated_at_ms: Date.now(),
    },
  });

  const meta = {
    source: SOURCE_SLUG,
    appliance: APPLIANCE_SLUG,
    agent_id: AGENT_ID,
    findings_saved: saved,
    outcome: 'scout_run_complete',
  };
  await xano.markSignalProcessed(signal.id, 'scout_run_complete', meta);
  log('scout_run_complete', meta);

  return { success: true, action: 'scout_run_complete', findings_saved: saved, agent_id: AGENT_ID };
}
