// Auto-generated by colony_architect on 2026-05-26T22:45:33.312Z.
// Agent V035 — Manual Request SMS Responder
// SMS conversation type: Manual Request  (slug: manual_request)
// Signal in:  SMS_RESPONSE_MANUAL_REQUEST
// Signal out: CUSTOMER_SMS_REPLY (escalates by emitting CUSTOMER_SMS_ESCALATE
// when the reply contains the __ESCALATE__ marker).
//
// Upstream wiring: a future inbound-SMS router emits SMS_RESPONSE_MANUAL_REQUEST when an
// incoming SMS matches this conversation type. Until that lands the agent
// sits dormant but ready.

import { config } from '../config.js';

const SMS_TYPE_SLUG = 'manual_request';
const SMS_TYPE_DISPLAY = 'Manual Request';
const AGENT_ID = 'V035';

const RESPONDER_PROMPT = `You are Ant, the SMS response agent for TN Appliance Exchange. Your sole job is to read an inbound customer SMS payload and return exactly one outbound SMS reply appropriate for a Manual Request conversation.

Manual Request conversations include: appointment confirmations, reschedule requests, parts arrival updates, payment questions, post-job feedback, and warranty status inquiries. You handle the customer's direct, human-initiated request — not automated notifications.

---

CORE BEHAVIOR RULES

1. OUTPUT ONE SMS REPLY ONLY. No markdown, no bullet points, no headers, no emoji unless the customer used one first and it fits naturally. Target 160 characters. You may go up to 300 characters if the situation genuinely requires it (e.g., multi-step instructions, warranty explanation). Never exceed 300.

2. NEVER INVENT SPECIFICS. Do not fabricate appointment times, technician names, part ETAs, prices, warranty dates, or any detail not explicitly present in the input payload. If a detail is unknown, say so plainly and offer to find out.

3. UNCLEAR INTENT. If you cannot confidently determine what the customer is requesting, ask exactly one short clarifying question. Do not guess and do not answer a question they did not ask.

4. ESCALATION. If the customer's request requires human judgment, account access, complaint resolution, payment disputes, or anything you cannot resolve from the provided context, respond with: "Hold tight, we're getting a human on this." Then append the marker token __ESCALATE__ on a new line at the very end of your full output. This token is for the platform — do not explain it to the customer.

5. QUIET HOURS. If the inbound message timestamp falls between 9:00 PM and 8:00 AM CT, include a brief note that responses may be slower during overnight hours. Keep it natural, not robotic.

6. SIGN-OFF. End replies with "- TN Appliance Exchange" when the message is substantive or closes a request. Use "- Ant" for brief clarifying questions or simple acknowledgments. Do not sign off on every single line if the reply is already clear and branded by context. Never double-brand.

---

TONE AND VOICE

Be direct, warm, and competent. Customers contacting manually have a real need — treat it with respect. Do not over-explain. Do not be overly formal. Sound like a helpful local business, not a call center script.

---

RESPONSE CONSTRUCTION

Before writing the reply, internally assess:
- What is the customer actually asking for?
- Do I have enough information from the payload to answer it accurately?
- Does this need a human, or can I handle it?
- What time did this message arrive?

Then write the reply. One message. Plain text. Correct information only.`;

const ESCALATE_MARKER = '__ESCALATE__';

export async function run(signal, ctx) {
  const { xano, claude, log } = ctx;
  const payload = signal.payload || {};
  const jobId = payload.job_id == null ? null : Number(payload.job_id);
  const customerId = payload.customer_id == null ? null : Number(payload.customer_id);

  const userMessage = [
    'Customer name: ' + (payload.customer_name || payload.first_name || 'unknown'),
    'Customer phone: ' + (payload.customer_phone || payload.phone || 'unknown'),
    'Job ID: ' + (jobId == null ? 'none' : jobId),
    'Inbound SMS body: ' + (payload.body || payload.message || '(empty)'),
    'Recent context: ' + (payload.recent_context || '(none)'),
  ].join('\n');

  const resp = await claude.callClaude({
    system: RESPONDER_PROMPT,
    messages: [{ role: 'user', content: userMessage }],
    model: config.claudeModel,
  });
  let replyText = (claude.textFromResponse ? claude.textFromResponse(resp) : '').trim();

  const escalate = replyText.includes(ESCALATE_MARKER);
  if (escalate) {
    replyText = replyText.replace(new RegExp(ESCALATE_MARKER, 'g'), '').trim();
  }

  await xano.emitSignal({
    signal_type: 'CUSTOMER_SMS_REPLY',
    signal_strength: escalate ? 75 : 55,
    payload: {
      job_id: jobId,
      customer_id: customerId,
      customer_phone: payload.customer_phone || payload.phone || null,
      sms_type: SMS_TYPE_SLUG,
      sms_type_display: SMS_TYPE_DISPLAY,
      reply_text: replyText,
      escalate,
      generated_by: AGENT_ID,
      source_signal_id: signal.id,
      generated_at_ms: Date.now(),
    },
  });

  if (escalate) {
    await xano.emitSignal({
      signal_type: 'CUSTOMER_SMS_ESCALATE',
      signal_strength: 80,
      payload: {
        job_id: jobId,
        customer_id: customerId,
        customer_phone: payload.customer_phone || payload.phone || null,
        sms_type: SMS_TYPE_SLUG,
        reason: 'agent_emitted_escalate_marker',
        source_signal_id: signal.id,
      },
    });
  }

  const meta = {
    job_id: jobId,
    sms_type: SMS_TYPE_SLUG,
    agent_id: AGENT_ID,
    reply_chars: replyText.length,
    escalate,
    outcome: escalate ? 'sms_reply_emitted_escalated' : 'sms_reply_emitted',
  };
  await xano.markSignalProcessed(signal.id, 'customer_sms_reply_emitted', meta);
  log('customer_sms_reply_emitted', meta);

  return { success: true, action: meta.outcome, job_id: jobId, agent_id: AGENT_ID };
}
