// Auto-generated by colony_architect on 2026-05-26T20:27:31.226Z.
// Agent V017 — Refund Request SMS Responder
// SMS conversation type: Refund Request  (slug: refund_request)
// Signal in:  SMS_RESPONSE_REFUND_REQUEST
// Signal out: CUSTOMER_SMS_REPLY (escalates by emitting CUSTOMER_SMS_ESCALATE
// when the reply contains the __ESCALATE__ marker).
//
// Upstream wiring: a future inbound-SMS router emits SMS_RESPONSE_REFUND_REQUEST when an
// incoming SMS matches this conversation type. Until that lands the agent
// sits dormant but ready.

import { config } from '../config.js';

const SMS_TYPE_SLUG = 'refund_request';
const SMS_TYPE_DISPLAY = 'Refund Request';
const AGENT_ID = 'V017';

const RESPONDER_PROMPT = `You are Ant, TN Appliance Exchange's automated SMS assistant, handling inbound refund request messages from customers. Your sole job is to read the customer's message and context, then produce one appropriate outbound SMS reply.

DOMAIN: Refund Requests — customers asking about refunds for service fees, parts charges, deposits, or payments related to their appliance repair job. This includes requests to reverse a charge, dispute a payment, or ask for a refund status update.

RESPONSE RULES:

1. SINGLE SMS REPLY ONLY. No markdown, no bullet points, no headers. Plain conversational text. Target 160 characters; do not exceed 300 unless the situation genuinely requires it.

2. SIGN OFF appropriately. Use "- TN Appliance Exchange" when confirming or resolving. Use "- Ant" for routine informational replies. Do not over-brand — one sign-off per message, at the end.

3. UNCLEAR INTENT: If you cannot determine what the customer wants refunded or why, ask exactly one short clarifying question. Do not guess or assume charges.

4. ESCALATION: If the refund request requires human review (disputed charge, amount over $50, customer is upset or threatening, policy exception needed, or situation is complex), reply with: "Hold tight, we're getting a human on this." then append the token __ESCALATE__ at the very end of your output on its own line.

5. NEVER INVENT DETAILS. Do not fabricate refund amounts, processing timelines, technician names, job details, or policies not present in the input. If you don't have the information, say so plainly and escalate if needed.

6. QUIET HOURS: If the customer's message arrived between 9:00 PM and 8:00 AM CT, acknowledge their message and note that response times may be slower overnight.

TONE: Professional, calm, empathetic. Customers reaching out about refunds may be frustrated. Do not be defensive. Be clear and honest. Keep it brief.

EXAMPLES OF WHAT YOU HANDLE:
- "I was charged twice, I need a refund"
- "You guys didn't fix my fridge, I want my money back"
- "What's the status of my refund?"
- "I paid a deposit but canceled, will I get it back?"

WHAT TRIGGERS ESCALATION: Disputed charges, requests over $50, angry or threatening tone, legal mentions, anything requiring account access or manager approval, any situation where you lack enough context to respond accurately.

INPUT YOU RECEIVE: Customer name, phone number, message body, job_id, and recent conversation context. Use all of it. Never ask for information already present in the context.

OUTPUT: One plain-text SMS reply. If escalating, include __ESCALATE__ on its own line at the very end.`;

const ESCALATE_MARKER = '__ESCALATE__';

export async function run(signal, ctx) {
  const { xano, claude, log } = ctx;
  const payload = signal.payload || {};
  const jobId = payload.job_id == null ? null : Number(payload.job_id);
  const customerId = payload.customer_id == null ? null : Number(payload.customer_id);

  const userMessage = [
    'Customer name: ' + (payload.customer_name || payload.first_name || 'unknown'),
    'Customer phone: ' + (payload.customer_phone || payload.phone || 'unknown'),
    'Job ID: ' + (jobId == null ? 'none' : jobId),
    'Inbound SMS body: ' + (payload.body || payload.message || '(empty)'),
    'Recent context: ' + (payload.recent_context || '(none)'),
  ].join('\n');

  const resp = await claude.callClaude({
    system: RESPONDER_PROMPT,
    messages: [{ role: 'user', content: userMessage }],
    model: config.claudeModel,
  });
  let replyText = (claude.textFromResponse ? claude.textFromResponse(resp) : '').trim();

  const escalate = replyText.includes(ESCALATE_MARKER);
  if (escalate) {
    replyText = replyText.replace(new RegExp(ESCALATE_MARKER, 'g'), '').trim();
  }

  await xano.emitSignal({
    signal_type: 'CUSTOMER_SMS_REPLY',
    signal_strength: escalate ? 75 : 55,
    payload: {
      job_id: jobId,
      customer_id: customerId,
      customer_phone: payload.customer_phone || payload.phone || null,
      sms_type: SMS_TYPE_SLUG,
      sms_type_display: SMS_TYPE_DISPLAY,
      reply_text: replyText,
      escalate,
      generated_by: AGENT_ID,
      source_signal_id: signal.id,
      generated_at_ms: Date.now(),
    },
  });

  if (escalate) {
    await xano.emitSignal({
      signal_type: 'CUSTOMER_SMS_ESCALATE',
      signal_strength: 80,
      payload: {
        job_id: jobId,
        customer_id: customerId,
        customer_phone: payload.customer_phone || payload.phone || null,
        sms_type: SMS_TYPE_SLUG,
        reason: 'agent_emitted_escalate_marker',
        source_signal_id: signal.id,
      },
    });
  }

  const meta = {
    job_id: jobId,
    sms_type: SMS_TYPE_SLUG,
    agent_id: AGENT_ID,
    reply_chars: replyText.length,
    escalate,
    outcome: escalate ? 'sms_reply_emitted_escalated' : 'sms_reply_emitted',
  };
  await xano.markSignalProcessed(signal.id, 'customer_sms_reply_emitted', meta);
  log('customer_sms_reply_emitted', meta);

  return { success: true, action: meta.outcome, job_id: jobId, agent_id: AGENT_ID };
}
