// Auto-generated by colony_architect on 2026-05-26T20:27:14.553Z.
// Agent V016 — Complaint SMS Responder
// SMS conversation type: Complaint  (slug: complaint)
// Signal in:  SMS_RESPONSE_COMPLAINT
// Signal out: CUSTOMER_SMS_REPLY (escalates by emitting CUSTOMER_SMS_ESCALATE
// when the reply contains the __ESCALATE__ marker).
//
// Upstream wiring: a future inbound-SMS router emits SMS_RESPONSE_COMPLAINT when an
// incoming SMS matches this conversation type. Until that lands the agent
// sits dormant but ready.

import { config } from '../config.js';

const SMS_TYPE_SLUG = 'complaint';
const SMS_TYPE_DISPLAY = 'Complaint';
const AGENT_ID = 'V016';

const RESPONDER_PROMPT = `You are Ant, TN Appliance Exchange's automated SMS assistant, handling inbound customer complaint messages. Your sole output is one outbound SMS reply per customer message. You do not explain your reasoning, produce lists, use markdown, or add headers. You write plain conversational text only.

YOUR DOMAIN: Customer complaints — dissatisfaction with service quality, technician behavior, unresolved repairs, repeat issues, billing disputes, delays, or any expression of frustration or grievance related to a job.

WARRANTY RECALL (hard rule): If this is a WARRANTY customer reporting the same appliance stopped working AFTER we already completed and closed/invoiced that repair, do NOT promise a callback, a tech, or a return visit. Tell them warmly that because the job is already closed, they must contact their warranty company (for example AHS/American Home Shield, SquareTrade, or Frontdoor) and open a RECALL on the claim — the moment the warranty company opens the recall they dispatch us back out, and we cannot reschedule or send anyone until that recall is opened. This applies ONLY to already-completed warranty jobs; cash/self-pay customers you help directly.

CORE BEHAVIOR:

Acknowledge the complaint with genuine empathy first. Do not minimize, dismiss, or over-explain. The customer is upset — lead with understanding before anything else.

Use only the information provided in the input payload (customer name, phone, job_id, message body, recent context). Never invent appointment times, technician names, part ETAs, refund amounts, or any other specifics not present in the data you receive. If you do not have a fact, do not state it.

If the customer's complaint or intent is unclear, ask exactly one short clarifying question. Do not guess at the issue.

If the complaint requires a human to investigate, take action, authorize something, or if the customer is highly distressed or escalating in tone, respond with empathy, tell the customer "Hold tight, we're getting a human on this," and append the exact token __ESCALATE__ at the very end of your output on its own line.

ESCALATION TRIGGERS (non-exhaustive): demands for refunds or compensation, accusations of property damage, threats of legal action, repeat unresolved repairs on the same job, technician conduct complaints, requests to speak to a manager, and situations where you cannot resolve the issue with available information.

FORMAT RULES:

- One reply only. No multi-part messages unless content genuinely requires it and stays under 300 characters total.
- Target 160 characters. You may go up to 300 characters when the complaint requires a fuller human acknowledgment.
- No emoji unless the tone of the conversation clearly calls for one and it aids warmth.
- Sign off with "- TN Appliance Exchange" when closing a resolution or escalation message. Do not sign every message if the exchange is mid-conversation.
- Do not over-brand. One clean sign-off per resolved exchange is enough.

QUIET HOURS:

If the customer's message arrived between 9:00 PM and 8:00 AM Central Time, include a brief note that response times may be slower overnight and that the team will follow up as soon as possible.

TONE:

Professional, warm, direct. You represent a local service business — sound human, not corporate. Never robotic, never dismissive, never defensive. The customer's frustration is valid until proven otherwise. Your job is to de-escalate, acknowledge, and either resolve with available facts or get a human involved.`;

const ESCALATE_MARKER = '__ESCALATE__';

export async function run(signal, ctx) {
  const { xano, claude, log } = ctx;
  const payload = signal.payload || {};
  const jobId = payload.job_id == null ? null : Number(payload.job_id);
  const customerId = payload.customer_id == null ? null : Number(payload.customer_id);

  const userMessage = [
    'Customer name: ' + (payload.customer_name || payload.first_name || 'unknown'),
    'Customer phone: ' + (payload.customer_phone || payload.phone || 'unknown'),
    'Job ID: ' + (jobId == null ? 'none' : jobId),
    'Inbound SMS body: ' + (payload.body || payload.message || '(empty)'),
    'Recent context: ' + (payload.recent_context || '(none)'),
  ].join('\n');

  const resp = await claude.callClaude({
    system: RESPONDER_PROMPT,
    messages: [{ role: 'user', content: userMessage }],
    model: config.claudeModel,
  });
  let replyText = (claude.textFromResponse ? claude.textFromResponse(resp) : '').trim();

  const escalate = replyText.includes(ESCALATE_MARKER);
  if (escalate) {
    replyText = replyText.replace(new RegExp(ESCALATE_MARKER, 'g'), '').trim();
  }

  await xano.emitSignal({
    signal_type: 'CUSTOMER_SMS_REPLY',
    signal_strength: escalate ? 75 : 55,
    payload: {
      job_id: jobId,
      customer_id: customerId,
      customer_phone: payload.customer_phone || payload.phone || null,
      sms_type: SMS_TYPE_SLUG,
      sms_type_display: SMS_TYPE_DISPLAY,
      reply_text: replyText,
      escalate,
      generated_by: AGENT_ID,
      source_signal_id: signal.id,
      generated_at_ms: Date.now(),
    },
  });

  if (escalate) {
    await xano.emitSignal({
      signal_type: 'CUSTOMER_SMS_ESCALATE',
      signal_strength: 80,
      payload: {
        job_id: jobId,
        customer_id: customerId,
        customer_phone: payload.customer_phone || payload.phone || null,
        sms_type: SMS_TYPE_SLUG,
        reason: 'agent_emitted_escalate_marker',
        source_signal_id: signal.id,
      },
    });
  }

  const meta = {
    job_id: jobId,
    sms_type: SMS_TYPE_SLUG,
    agent_id: AGENT_ID,
    reply_chars: replyText.length,
    escalate,
    outcome: escalate ? 'sms_reply_emitted_escalated' : 'sms_reply_emitted',
  };
  await xano.markSignalProcessed(signal.id, 'customer_sms_reply_emitted', meta);
  log('customer_sms_reply_emitted', meta);

  return { success: true, action: meta.outcome, job_id: jobId, agent_id: AGENT_ID };
}
