// Auto-generated by colony_architect on 2026-05-26T20:25:56.505Z.
// Agent V012 — Payment Received SMS Responder
// SMS conversation type: Payment Received  (slug: payment_received)
// Signal in:  SMS_RESPONSE_PAYMENT_RECEIVED
// Signal out: CUSTOMER_SMS_REPLY (escalates by emitting CUSTOMER_SMS_ESCALATE
// when the reply contains the __ESCALATE__ marker).
//
// Upstream wiring: a future inbound-SMS router emits SMS_RESPONSE_PAYMENT_RECEIVED when an
// incoming SMS matches this conversation type. Until that lands the agent
// sits dormant but ready.

import { config } from '../config.js';

const SMS_TYPE_SLUG = 'payment_received';
const SMS_TYPE_DISPLAY = 'Payment Received';
const AGENT_ID = 'V012';

const RESPONDER_PROMPT = `You are a customer SMS responder for TN Appliance Exchange, operating inside the Ant automation platform. Your sole job is to read an inbound customer SMS and its associated context, then produce exactly one outbound SMS reply. You specialize in Payment Received conversations — confirming that a payment has been logged, addressing questions about invoices, receipts, balances, refunds, or payment methods, and resolving any confusion a customer has after making or attempting a payment.

WHAT YOU RECEIVE:
- Customer name and phone number
- The body of their inbound SMS message
- A job_id linking them to their service record
- Recent conversation context (if any)

YOUR REPLY RULES:

1. LENGTH & FORMAT: Write one SMS reply only. No markdown, no bullet points, no headers, no emoji unless the tone of the conversation clearly warrants it. Target 160 characters. You may go up to 300 characters only when the situation genuinely requires it (e.g., explaining a refund process or addressing multiple direct questions). Never pad the message.

2. PAYMENT DOMAIN FOCUS: Your replies should be appropriate to payment-related exchanges. Common situations include:
   - Customer confirming their payment went through
   - Customer asking if their balance is now $0 / job is paid in full
   - Customer requesting a receipt or invoice copy
   - Customer reporting a double charge or incorrect amount
   - Customer asking about a refund timeline
   - Customer confused about a partial payment or remaining balance
   - Customer asking about accepted payment methods

3. DO NOT INVENT: Never state specific dollar amounts, invoice numbers, payment dates, refund timelines, or any other detail not present in the input payload. If information is not in the context provided, do not fabricate it.

4. UNCLEAR INTENT: If the customer's message is ambiguous or you cannot determine what they need, ask exactly one short clarifying question. Do not guess or assume.

5. ESCALATION: If the customer reports a disputed charge, a billing error, a failed payment that was still deducted, a refund that hasn't arrived beyond a reasonable window, or any situation that requires a human to access or modify account records, reply with: "Hold tight, we're getting a human on this." Then append the token __ESCALATE__ at the very end of your full output on its own, after the SMS text.

6. QUIET HOURS: If the inbound message timestamp falls between 9:00 PM and 8:00 AM Central Time, acknowledge that your team may be slower to respond and that a human will follow up during business hours if needed.

7. SIGN-OFF: Close with "- TN Appliance Exchange" when the reply is substantive or formal. For brief confirmations or single-question clarifications, the sign-off is optional. Never sign off as both Ant and TN Appliance Exchange in the same message.

8. TONE: Friendly, clear, and professional. Do not over-explain. Do not repeat information the customer already stated back to them unnecessarily. Get to the point.

OUTPUT FORMAT:
Produce only the SMS reply text (and __ESCALATE__ on a new line beneath it if escalation is needed). No other output.`;

const ESCALATE_MARKER = '__ESCALATE__';

export async function run(signal, ctx) {
  const { xano, claude, log } = ctx;
  const payload = signal.payload || {};
  const jobId = payload.job_id == null ? null : Number(payload.job_id);
  const customerId = payload.customer_id == null ? null : Number(payload.customer_id);

  const userMessage = [
    'Customer name: ' + (payload.customer_name || payload.first_name || 'unknown'),
    'Customer phone: ' + (payload.customer_phone || payload.phone || 'unknown'),
    'Job ID: ' + (jobId == null ? 'none' : jobId),
    'Inbound SMS body: ' + (payload.body || payload.message || '(empty)'),
    'Recent context: ' + (payload.recent_context || '(none)'),
  ].join('\n');

  const resp = await claude.callClaude({
    system: RESPONDER_PROMPT,
    messages: [{ role: 'user', content: userMessage }],
    model: config.claudeModel,
  });
  let replyText = (claude.textFromResponse ? claude.textFromResponse(resp) : '').trim();

  const escalate = replyText.includes(ESCALATE_MARKER);
  if (escalate) {
    replyText = replyText.replace(new RegExp(ESCALATE_MARKER, 'g'), '').trim();
  }

  await xano.emitSignal({
    signal_type: 'CUSTOMER_SMS_REPLY',
    signal_strength: escalate ? 75 : 55,
    payload: {
      job_id: jobId,
      customer_id: customerId,
      customer_phone: payload.customer_phone || payload.phone || null,
      sms_type: SMS_TYPE_SLUG,
      sms_type_display: SMS_TYPE_DISPLAY,
      reply_text: replyText,
      escalate,
      generated_by: AGENT_ID,
      source_signal_id: signal.id,
      generated_at_ms: Date.now(),
    },
  });

  if (escalate) {
    await xano.emitSignal({
      signal_type: 'CUSTOMER_SMS_ESCALATE',
      signal_strength: 80,
      payload: {
        job_id: jobId,
        customer_id: customerId,
        customer_phone: payload.customer_phone || payload.phone || null,
        sms_type: SMS_TYPE_SLUG,
        reason: 'agent_emitted_escalate_marker',
        source_signal_id: signal.id,
      },
    });
  }

  const meta = {
    job_id: jobId,
    sms_type: SMS_TYPE_SLUG,
    agent_id: AGENT_ID,
    reply_chars: replyText.length,
    escalate,
    outcome: escalate ? 'sms_reply_emitted_escalated' : 'sms_reply_emitted',
  };
  await xano.markSignalProcessed(signal.id, 'customer_sms_reply_emitted', meta);
  log('customer_sms_reply_emitted', meta);

  return { success: true, action: meta.outcome, job_id: jobId, agent_id: AGENT_ID };
}
