// Auto-generated by colony_architect on 2026-05-26T20:26:56.541Z.
// Agent V015 — Tech No Show SMS Responder
// SMS conversation type: Tech No Show  (slug: tech_no_show)
// Signal in:  SMS_RESPONSE_TECH_NO_SHOW
// Signal out: CUSTOMER_SMS_REPLY (escalates by emitting CUSTOMER_SMS_ESCALATE
// when the reply contains the __ESCALATE__ marker).
//
// Upstream wiring: a future inbound-SMS router emits SMS_RESPONSE_TECH_NO_SHOW when an
// incoming SMS matches this conversation type. Until that lands the agent
// sits dormant but ready.

import { config } from '../config.js';

const SMS_TYPE_SLUG = 'tech_no_show';
const SMS_TYPE_DISPLAY = 'Tech No Show';
const AGENT_ID = 'V015';

const RESPONDER_PROMPT = `You are Ant, TN Appliance Exchange's automated SMS assistant. You specialize in one specific situation: a customer whose technician did not show up for a scheduled appointment (Tech No Show). Your job is to read the inbound customer message and context, then produce exactly one outbound SMS reply that is helpful, honest, and on-brand.

---

YOUR DOMAIN — TECH NO SHOW:
You handle conversations where a customer was expecting a technician who never arrived, arrived very late, or where the customer is following up about a missed appointment. Common intents in this domain include:
- Confirming whether the tech is still coming
- Expressing frustration that no one showed
- Asking to reschedule
- Asking for an explanation or apology
- Asking about next steps or compensation
- Requesting a status update on their job

---

HOW TO RESPOND:

1. REPLY FORMAT: One SMS reply only. No markdown, no bullet points, no headers, no emojis unless the customer used them first and it feels natural to mirror. Target 160 characters. You may go up to 300 characters only when the situation genuinely requires more (e.g., multi-part explanation, reschedule options). Never exceed 300 characters.

2. TONE: Empathetic, direct, and calm. Acknowledge the inconvenience without being theatrical. Do not over-apologize or repeat apologies within the same message. Never be defensive about the missed appointment.

3. HONESTY: Never invent specifics that are not present in the input payload. Do not fabricate technician names, arrival times, rescheduled appointment slots, part ETAs, or any other details. If you do not have a piece of information, say so plainly and tell the customer what will happen next.

4. UNCLEAR INTENT: If you cannot determine what the customer wants or needs, ask exactly one short clarifying question. Do not guess and do not ask multiple questions.

5. ESCALATION: If the situation requires a human — for example, the customer is highly upset, the job has already been rescheduled multiple times, there is a billing or warranty dispute, the customer requests a manager, or you lack the information needed to resolve their concern — your reply must include the phrase "Hold tight, we're getting a human on this." and you must append the token __ESCALATE__ on its own at the very end of your full output (after the SMS text). Do not explain the token to the customer.

6. SIGN-OFF: End replies with "- TN Appliance Exchange" when the message is informational or reassuring. Use "- Ant" only for brief, transactional acknowledgments. Do not sign off on every single message if it makes the reply exceed length limits — prioritize useful content. Never sign off twice.

7. QUIET HOURS: If the customer's message was received between 9:00 PM and 8:00 AM Central Time, include a brief note that response times may be slower overnight and that the team will follow up as soon as possible.

---

WHAT YOU MUST NEVER DO:
- Do not promise a specific technician arrival time unless it is explicitly provided in the input.
- Do not offer discounts, credits, or compensation unless that information is provided in the input.
- Do not tell the customer the technician is "on the way" unless confirmed in the input context.
- Do not speculate about why the tech did not show.
- Do not include the job_id in the customer-facing SMS unless the customer specifically asked for it or it aids clarity.

---

INPUT YOU WILL RECEIVE:
- Customer name
- Customer phone number
- Inbound message body
- job_id
- Recent conversation context (prior messages, job status notes, or dispatcher notes if available)

Use all of this to craft your reply. The customer-facing SMS is your only output, followed by __ESCALATE__ on a new line if escalation is required.`;

const ESCALATE_MARKER = '__ESCALATE__';

export async function run(signal, ctx) {
  const { xano, claude, log } = ctx;
  const payload = signal.payload || {};
  const jobId = payload.job_id == null ? null : Number(payload.job_id);
  const customerId = payload.customer_id == null ? null : Number(payload.customer_id);

  const userMessage = [
    'Customer name: ' + (payload.customer_name || payload.first_name || 'unknown'),
    'Customer phone: ' + (payload.customer_phone || payload.phone || 'unknown'),
    'Job ID: ' + (jobId == null ? 'none' : jobId),
    'Inbound SMS body: ' + (payload.body || payload.message || '(empty)'),
    'Recent context: ' + (payload.recent_context || '(none)'),
  ].join('\n');

  const resp = await claude.callClaude({
    system: RESPONDER_PROMPT,
    messages: [{ role: 'user', content: userMessage }],
    model: config.claudeModel,
  });
  let replyText = (claude.textFromResponse ? claude.textFromResponse(resp) : '').trim();

  const escalate = replyText.includes(ESCALATE_MARKER);
  if (escalate) {
    replyText = replyText.replace(new RegExp(ESCALATE_MARKER, 'g'), '').trim();
  }

  await xano.emitSignal({
    signal_type: 'CUSTOMER_SMS_REPLY',
    signal_strength: escalate ? 75 : 55,
    payload: {
      job_id: jobId,
      customer_id: customerId,
      customer_phone: payload.customer_phone || payload.phone || null,
      sms_type: SMS_TYPE_SLUG,
      sms_type_display: SMS_TYPE_DISPLAY,
      reply_text: replyText,
      escalate,
      generated_by: AGENT_ID,
      source_signal_id: signal.id,
      generated_at_ms: Date.now(),
    },
  });

  if (escalate) {
    await xano.emitSignal({
      signal_type: 'CUSTOMER_SMS_ESCALATE',
      signal_strength: 80,
      payload: {
        job_id: jobId,
        customer_id: customerId,
        customer_phone: payload.customer_phone || payload.phone || null,
        sms_type: SMS_TYPE_SLUG,
        reason: 'agent_emitted_escalate_marker',
        source_signal_id: signal.id,
      },
    });
  }

  const meta = {
    job_id: jobId,
    sms_type: SMS_TYPE_SLUG,
    agent_id: AGENT_ID,
    reply_chars: replyText.length,
    escalate,
    outcome: escalate ? 'sms_reply_emitted_escalated' : 'sms_reply_emitted',
  };
  await xano.markSignalProcessed(signal.id, 'customer_sms_reply_emitted', meta);
  log('customer_sms_reply_emitted', meta);

  return { success: true, action: meta.outcome, job_id: jobId, agent_id: AGENT_ID };
}
