// troubleshooting-content.js — the curated, expert-authored source data for the
// authority content library. Each entry becomes a deep, honest symptom page under
// /fix/ with FAQ + HowTo + Breadcrumb schema, built to be the answer a voice
// assistant or AI quotes for "my <appliance> <symptom> — what do I do?".
//
// QUALITY RULE: real, accurate repair knowledge only. DIY steps stay SAFE (unplug
// first, visual/simple checks); the actual repair routes to us (local) or the
// nationwide video diagnostic. Gas/sealed-system work is always "call a pro".
// Add an entry + re-run scripts/build-troubleshooting-pages.js to grow the library.
'use strict';

module.exports = [
  {
    slug: 'washer-wont-drain',
    appliance: 'Washer',
    question: 'My washer won\'t drain — what do I do?',
    metaTitle: 'Washer Won\'t Drain? Causes & Fixes From a Real Technician',
    metaDesc: 'A washer that won\'t drain is usually a clogged pump filter, a kinked drain hose, or a failed drain pump. Here\'s how to tell — and get it fixed.',
    intro: 'A washer that fills and washes but leaves standing water almost always comes down to one thing: something between the tub and your drain is blocked or the pump has quit. The good news is that this is one of the most common — and most affordable — repairs we do. Here are the real causes, in the order we check them, plus the safe things you can look at yourself before you call anyone.',
    safety: 'Always unplug the washer before touching the pump or hoses, and have towels ready — there will be trapped water.',
    causes: [
      { name: 'Clogged pump filter / coin trap', why: 'Front-load washers (and many high-efficiency top-loaders) have a small filter that catches coins, hair pins, and lint. When it clogs, water can\'t leave the tub. This is the single most common cause and often a 10-minute fix.', diy: 'Unplug the washer, find the small access panel at the bottom front, put down towels, and slowly open the filter to drain and clear it.', difficulty: 'Easy' },
      { name: 'Kinked or clogged drain hose', why: 'The hose running to your standpipe or disposal can kink behind the machine or clog with lint and gunk, especially where it connects.', diy: 'Pull the washer out, check the hose for kinks or crush points, and make sure it isn\'t pushed too far down the drain (which causes siphoning).', difficulty: 'Easy' },
      { name: 'Failed drain pump', why: 'The drain pump is a small motor that pushes water out. When the bearings wear or the motor burns out, you\'ll often hear a humming or grinding with no water movement. This is a common, affordable part.', diy: 'Listen during the drain cycle — a hum with no draining, or silence, points at the pump. Replacement is a real repair, not a DIY check.', difficulty: 'Pro' },
      { name: 'Object stuck in the pump impeller', why: 'A sock, underwire, or coin can jam the pump impeller so it can\'t spin.', diy: 'With the machine unplugged and the filter open, you can sometimes feel for and remove a foreign object at the impeller.', difficulty: 'Moderate' },
      { name: 'Lid switch or door lock', why: 'Most washers won\'t advance to drain and spin if the machine doesn\'t think the lid or door is securely closed.', diy: 'Confirm the door latches firmly. A failed lid switch or door lock is a technician repair.', difficulty: 'Pro' },
    ],
    repairReplace: 'A drain pump, filter clog, or hose issue is an inexpensive fix and is almost always worth repairing — on any washer, at any age. The only time replacement enters the conversation is when a drain problem is paired with other major failures (bad bearings plus a dead control board, for example).',
    faqs: [
      { q: 'Why is there standing water in my washer?', a: 'Standing water means the drain step failed. The usual causes are a clogged pump filter, a kinked or clogged drain hose, or a worn-out drain pump. Start by unplugging the machine and checking the filter at the bottom front.' },
      { q: 'Can I fix a washer that won\'t drain myself?', a: 'You can safely check and clear the pump filter, inspect the drain hose for kinks, and look for a stuck object at the impeller — all with the machine unplugged. If the pump itself has failed or the lid switch is bad, that\'s a technician repair.' },
      { q: 'Is a washer that won\'t drain worth fixing?', a: 'Almost always yes. The most common causes — a clogged filter, a hose, or a drain pump — are inexpensive repairs on any age of washer.' },
    ],
  },
  {
    slug: 'dryer-not-heating',
    appliance: 'Dryer',
    question: 'My dryer runs but won\'t heat — what do I do?',
    metaTitle: 'Dryer Not Heating? The Real Causes & How to Fix It',
    metaDesc: 'A dryer that runs but won\'t heat is usually a heating element, a blown thermal fuse from a clogged vent, or a lost 240V leg. Here\'s how to diagnose it.',
    intro: 'When a dryer tumbles fine but everything comes out cold and damp, the problem is in the heat circuit — not the motor. Nine times out of ten it traces back to one of a few affordable parts, and very often the root cause is a clogged vent that overheated and tripped a safety device. Here is exactly what we check, and the safe things you can look at first.',
    safety: 'Unplug an electric dryer before checking anything internal. For GAS dryers, do not attempt igniter or gas-valve work yourself — that is a call-a-pro repair.',
    causes: [
      { name: 'Clogged vent (the hidden root cause)', why: 'A restricted vent traps heat inside the dryer and trips the thermal fuse or high-limit thermostat as a safety measure. Fix the part without clearing the vent and it just fails again. It\'s also the #1 dryer fire risk.', diy: 'Disconnect and clear the vent hose and exhaust duct. If drying has been slow for weeks, this is very likely part of your problem.', difficulty: 'Easy' },
      { name: 'Heating element', why: 'The element produces the heat. On electric dryers it burns out over time and the dryer runs cold. This is a common, affordable part.', diy: 'No safe DIY test without a meter and disassembly — but a dryer that tumbles normally with zero heat often points here.', difficulty: 'Pro' },
      { name: 'Blown thermal fuse', why: 'A one-time safety fuse that cuts heat (or all power, depending on model) when the dryer overheats — usually because of that clogged vent.', diy: 'Clear the vent first. The fuse itself is a technician replacement, and it must be paired with fixing the airflow that blew it.', difficulty: 'Pro' },
      { name: 'Thermal cutoff / high-limit thermostat', why: 'These regulate and cap the temperature. When they fail, heat can drop out.', diy: 'Not a DIY check. Diagnosed and replaced by a technician.', difficulty: 'Pro' },
      { name: 'Lost 240V leg (electric dryers)', why: 'Electric dryers use two 120V legs. If one breaker leg trips or fails, the motor still runs on one leg but the element gets no power — so it tumbles but won\'t heat.', diy: 'Check your breaker: fully switch the dryer\'s double breaker off and back on. If a leg is lost at the panel, that\'s an electrical issue.', difficulty: 'Easy' },
      { name: 'Gas igniter or flame sensor (gas dryers)', why: 'On gas models a weak igniter or bad flame sensor stops the burner from lighting, so no heat.', diy: 'Do not DIY gas components. This is a technician repair for safety.', difficulty: 'Pro' },
    ],
    repairReplace: 'Heating elements, fuses, thermostats, and igniters are all affordable parts, and the labor is straightforward — a no-heat dryer is well worth repairing in almost every case. Clearing the vent at the same time is what keeps the fix from failing again.',
    faqs: [
      { q: 'Why does my dryer run but not get hot?', a: 'The motor and the heat circuit are separate. If it tumbles but stays cold, the issue is in the heat side — most often a heating element, a thermal fuse blown by a clogged vent, or (on electric dryers) a lost 240V breaker leg.' },
      { q: 'Can a clogged vent stop a dryer from heating?', a: 'Yes. A restricted vent traps heat and trips the thermal fuse or high-limit thermostat as a safety response, cutting the heat. Clearing the vent is the first thing to do — and it prevents a fire hazard.' },
      { q: 'Is it worth fixing a dryer that won\'t heat?', a: 'Usually yes. The common causes are inexpensive parts and a quick repair. Replacement only makes sense if the dryer has other major problems on top of the no-heat issue.' },
    ],
  },
  {
    slug: 'refrigerator-not-cooling',
    appliance: 'Refrigerator',
    question: 'My refrigerator stopped cooling — what do I do?',
    metaTitle: 'Refrigerator Not Cooling? Causes, Checks & When to Call',
    metaDesc: 'A fridge that runs but won\'t cool is often dirty condenser coils, a failed evaporator fan, or a defrost problem. Here\'s how to tell what\'s wrong.',
    intro: 'A refrigerator that\'s running but not getting cold is stressful — you\'re watching food go warm. Before you assume the worst (an expensive compressor), know that most "not cooling" calls we get turn out to be an affordable fix: airflow, a fan, or the defrost system. Here\'s how we work through it, and what you can safely check right now.',
    safety: 'Unplug the refrigerator before cleaning coils or checking fans. Sealed-system and compressor work requires a licensed technician — never attempt it yourself.',
    causes: [
      { name: 'Dirty condenser coils', why: 'Coils caked in dust and pet hair can\'t release heat, so the fridge runs constantly and still won\'t cool. This is the most common and most preventable cause.', diy: 'Unplug the fridge, find the coils (behind the kick plate or on the back), and vacuum them clean.', difficulty: 'Easy' },
      { name: 'Evaporator fan motor', why: 'This fan moves cold air from the freezer coils into the fridge compartment. If it fails, the freezer may stay cold-ish while the fridge section warms up.', diy: 'Listen: open the freezer and press the door switch — you should hear the fan. Silence points here. Replacement is a technician repair.', difficulty: 'Pro' },
      { name: 'Defrost system failure', why: 'Frost builds on the evaporator coils and blocks airflow when the defrost heater, thermostat, or timer/board fails. Classic sign: freezer works, fridge doesn\'t, and you see frost buildup.', diy: 'If you see heavy frost on the back freezer wall, that\'s the clue. The repair is a technician job.', difficulty: 'Pro' },
      { name: 'Condenser fan motor', why: 'On coil-in-back-cabinet models, this fan cools the compressor and coils. If it stops, the system overheats and cooling drops.', diy: 'Not a safe DIY check. Diagnosed by a technician.', difficulty: 'Pro' },
      { name: 'Start relay / compressor', why: 'The compressor is the heart of the system. A failed start relay (cheap) can stop it from running; a failed compressor (expensive) is the rare worst case.', diy: 'Not DIY. A technician confirms whether it\'s the affordable relay or the compressor itself.', difficulty: 'Pro' },
      { name: 'Overpacked or blocked vents', why: 'Blocking the interior air vents with food stops cold air from circulating.', diy: 'Make sure nothing is jammed against the vents inside the fridge and freezer.', difficulty: 'Easy' },
    ],
    repairReplace: 'Coils, fans, start relays, and defrost parts are all affordable and worth fixing. The one expensive scenario is a failed compressor or a sealed-system leak — and that\'s exactly the situation where our honest repair-vs-replace math matters most, so you don\'t sink money into a fridge that isn\'t worth it. We tell you straight.',
    faqs: [
      { q: 'Why is my fridge running but not cold?', a: 'Running-but-warm usually means airflow or a fan, not the compressor. The most common causes are dirty condenser coils, a failed evaporator fan, or a defrost-system problem building frost on the coils. Start by vacuuming the coils.' },
      { q: 'What can I check before calling a refrigerator repair tech?', a: 'Safely: vacuum the condenser coils, make sure the interior vents aren\'t blocked by food, listen for the evaporator fan when you press the freezer door switch, and look for heavy frost on the back freezer wall.' },
      { q: 'Is it worth repairing a refrigerator that won\'t cool?', a: 'Most causes — coils, fans, relays, defrost parts — are affordable and worth fixing. The exception is a failed compressor or sealed-system leak; for those we give you honest repair-vs-replace numbers before you spend a dime.' },
    ],
  },
  {
    slug: 'dishwasher-wont-drain',
    appliance: 'Dishwasher',
    question: 'My dishwasher won\'t drain — what do I do?',
    metaTitle: 'Dishwasher Won\'t Drain? Simple Causes & Fixes',
    metaDesc: 'Standing water in your dishwasher is usually a clogged filter, a garbage-disposal knockout plug, or the drain pump. Here\'s how to clear it.',
    intro: 'Water in the bottom of the dishwasher after a cycle is a classic — and usually simple — problem. A lot of the time it\'s something you can clear in a few minutes, especially if a new garbage disposal was just installed. Here are the causes in the order we check them.',
    safety: 'Turn the dishwasher off at the breaker before reaching near the drain pump. Scoop out standing water with a cup and towel first.',
    causes: [
      { name: 'Clogged filter or sump', why: 'Food, grease, and debris build up in the filter at the bottom of the tub and block drainage. This is the most common cause and an easy clean.', diy: 'Remove the bottom rack, twist out the filter, and rinse it under hot water. Clear any debris in the sump.', difficulty: 'Easy' },
      { name: 'Garbage disposal knockout plug', why: 'If a new garbage disposal was recently installed and the dishwasher won\'t drain, the installer likely forgot to knock out the drain plug inside the disposal inlet. Extremely common.', diy: 'Check under the sink — if a new disposal went in recently, the knockout plug may need to be removed from the disposal\'s dishwasher inlet.', difficulty: 'Moderate' },
      { name: 'Clogged or kinked drain hose', why: 'The hose from the dishwasher to the disposal or standpipe can clog or kink.', diy: 'Check the hose under the sink for kinks. A deep clog is a technician clear-out.', difficulty: 'Moderate' },
      { name: 'Drain pump', why: 'The pump that pushes water out can fail or jam with glass or debris.', diy: 'A humming pump with no draining points here. Replacement is a technician repair.', difficulty: 'Pro' },
      { name: 'Check valve stuck', why: 'A one-way valve keeps drained water from flowing back; if it sticks, drainage suffers.', diy: 'Not a typical DIY check. Diagnosed by a technician.', difficulty: 'Pro' },
    ],
    repairReplace: 'The vast majority of dishwasher drain problems are cheap fixes — a filter clean, a knockout plug, or a hose. Even a drain pump is an affordable part. A dishwasher that won\'t drain is almost always worth repairing.',
    faqs: [
      { q: 'Why is there water at the bottom of my dishwasher?', a: 'A small amount is normal; a full pool after a cycle means it didn\'t drain. The usual causes are a clogged filter, a garbage-disposal knockout plug that was never removed, a kinked drain hose, or a failed drain pump.' },
      { q: 'I just got a new garbage disposal and my dishwasher won\'t drain — why?', a: 'This is very common. New disposals ship with a knockout plug in the dishwasher inlet that must be removed during installation. If it was missed, the dishwasher can\'t drain into the disposal. Removing the plug fixes it.' },
      { q: 'Can I fix a dishwasher that won\'t drain myself?', a: 'Often yes — cleaning the filter and checking the disposal knockout are safe, simple steps. If the drain pump has failed or there\'s a deep clog, that\'s a technician repair.' },
    ],
  },
  {
    slug: 'oven-not-heating',
    appliance: 'Oven',
    question: 'My oven won\'t heat — what do I do?',
    metaTitle: 'Oven Won\'t Heat? Electric & Gas Causes Explained',
    metaDesc: 'An oven that won\'t heat is usually a bake element (electric) or a weak igniter (gas). Here\'s how to tell which — and what\'s safe to check.',
    intro: 'An oven that won\'t come up to temperature splits cleanly by fuel type: on electric ovens it\'s almost always the bake element, and on gas ovens it\'s almost always the igniter. Both are common, affordable repairs. Here\'s how to tell what you\'re dealing with, and the safe checks first.',
    safety: 'For GAS ovens, do not attempt igniter or gas-valve work yourself — call a technician. For electric ovens, cut power at the breaker before inspecting anything.',
    causes: [
      { name: 'Bake element (electric ovens)', why: 'The bottom heating element is the most common electric-oven failure. A failed element often has a visible blister, break, or burn spot and won\'t glow.', diy: 'Look at the element with the oven cool: a visible break or burn mark is a strong sign. Replacement is a straightforward repair.', difficulty: 'Moderate' },
      { name: 'Oven igniter (gas ovens)', why: 'The igniter both lights the gas and tells the valve to open. As it weakens with age it glows but no longer gets hot enough to open the valve — so the oven doesn\'t heat. This is the #1 gas-oven failure.', diy: 'You may see the igniter glow but no flame. Do not DIY gas parts — this is a technician repair for safety.', difficulty: 'Pro' },
      { name: 'Temperature sensor', why: 'The oven\'s temperature sensor tells the control how hot it is. A failed sensor can cause no-heat or wildly wrong temperatures.', diy: 'Not a DIY check. Diagnosed by a technician.', difficulty: 'Pro' },
      { name: 'Control board or thermal fuse', why: 'A failed control board or a tripped thermal fuse can cut power to the heat circuit.', diy: 'Not DIY. A technician confirms and replaces.', difficulty: 'Pro' },
      { name: 'Wrong mode or lock', why: 'Delay-start, Sabbath mode, or a self-clean lock can make an oven seem dead.', diy: 'Confirm the oven isn\'t in a delay, lock, or self-clean cycle before assuming a failure.', difficulty: 'Easy' },
    ],
    repairReplace: 'A bake element or a gas igniter is an affordable part and a quick repair — an oven that won\'t heat is well worth fixing in nearly every case. Replacement only makes sense on a very old range with multiple failing systems.',
    faqs: [
      { q: 'Why won\'t my electric oven heat up?', a: 'On an electric oven the usual culprit is a failed bake element — often with a visible blister or break. A bad temperature sensor or control board is possible but less common. The bake element is an affordable, common repair.' },
      { q: 'My gas oven igniter glows but there\'s no flame — why?', a: 'That\'s the classic sign of a weak igniter. As it ages it still glows but can no longer get hot enough to open the gas valve, so the oven never heats. The igniter needs replacing — and because it\'s gas, it should be done by a technician.' },
      { q: 'Is an oven that won\'t heat worth repairing?', a: 'Usually yes. The two most common causes — an electric bake element or a gas igniter — are inexpensive parts with quick labor.' },
    ],
  },
  {
    slug: 'washer-not-spinning',
    appliance: 'Washer',
    question: 'My washer won\'t spin — what do I do?',
    metaTitle: 'Washer Won\'t Spin? Causes and What to Check First',
    metaDesc: 'A washer that won\'t spin is often a drain problem, an unbalanced load, a lid switch, or a worn belt or coupler. Here\'s how to narrow it down.',
    intro: 'A washer that won\'t spin leaves you with a soaking, heavy load. The first thing to know: a machine won\'t spin until it has fully drained — so a spin problem is very often really a drain problem. After that, it\'s usually a switch, a belt, or (on top-loaders) the coupler. Here\'s how we sort it out.',
    safety: 'Unplug the washer before checking the lid switch, belt, or coupler, and redistribute a wet load carefully — it\'s heavy.',
    causes: [
      { name: 'It hasn\'t fully drained', why: 'Most washers refuse to spin until the water is out. If there\'s standing water, fix the drain issue first — the spin will usually return with it.', diy: 'Check for standing water and clear the pump filter/drain hose (see our washer-won\'t-drain guide).', difficulty: 'Easy' },
      { name: 'Unbalanced load', why: 'A bulky or lopsided load (a comforter, towels bunched to one side) trips the balance sensor and cancels the spin to protect the machine.', diy: 'Open the lid, redistribute the load evenly, and restart the spin.', difficulty: 'Easy' },
      { name: 'Lid switch or door lock', why: 'The machine won\'t spin if it doesn\'t sense a securely closed lid or locked door. A failed switch is a common cause.', diy: 'Confirm the lid latches firmly and you hear/feel it engage. A failed switch is a technician repair.', difficulty: 'Pro' },
      { name: 'Motor coupler (top-loaders)', why: 'On many top-load washers a plastic coupler connects the motor to the transmission and wears out — the washer runs but won\'t agitate or spin.', diy: 'Not a DIY check, but a very common and affordable repair on top-loaders.', difficulty: 'Pro' },
      { name: 'Drive belt', why: 'A stretched, slipped, or broken belt stops the drum from spinning.', diy: 'Not a DIY check. A technician inspects and replaces the belt.', difficulty: 'Pro' },
    ],
    repairReplace: 'Lid switches, couplers, and belts are all inexpensive parts with reasonable labor — a no-spin washer is almost always worth repairing. The only time to reconsider is when the no-spin is paired with bad main bearings (a loud, expensive repair) on an older machine.',
    faqs: [
      { q: 'Why won\'t my washer spin the water out?', a: 'Most washers won\'t spin until they\'ve fully drained, so a no-spin problem is often really a drain problem. Beyond that, the common causes are an unbalanced load, a failed lid switch or door lock, or a worn belt or motor coupler.' },
      { q: 'My washer fills and washes but won\'t spin — what\'s wrong?', a: 'If it agitates but won\'t spin, look at the drain first (it must be empty to spin), then the lid switch, and on top-loaders the motor coupler. On front-loaders, the door lock and belt are common causes.' },
      { q: 'Is a washer that won\'t spin worth fixing?', a: 'Usually yes — lid switches, couplers, and belts are affordable. Reconsider only if it\'s paired with worn bearings on an older machine, and we\'ll give you the honest numbers.' },
    ],
  },
  {
    slug: 'freezer-not-freezing',
    appliance: 'Freezer',
    question: 'My freezer isn\'t freezing — what do I do?',
    metaTitle: 'Freezer Not Freezing? Causes & Fixes From a Real Technician',
    metaDesc: 'A freezer that runs but won\'t freeze is usually a failed defrost system, a stuck evaporator fan, a bad start relay, or frost blocking airflow. Here\'s how to tell — and get it fixed.',
    intro: 'A freezer that hums along but won\'t get cold is racing a clock — your food. On chest and upright freezers the cause is almost always one of a short list: the defrost system, the fan that moves cold air, the little relay that starts the compressor, or frost that has quietly blocked the airflow. Here are the real causes in the order a technician checks them, plus the safe things you can look at yourself first.',
    safety: 'Unplug the freezer before checking the relay or fan, and don\'t attempt any sealed-system or refrigerant work yourself — that\'s licensed EPA-608 work.',
    causes: [
      { name: 'Failed defrost system (heater, thermostat, or timer)', why: 'On frost-free freezers a defrost cycle melts frost off the coils periodically. When the heater, defrost thermostat, or timer/control fails, frost builds on the evaporator until it blocks airflow and the freezer stops cooling — even though the compressor runs.', diy: 'Unplug the freezer and look at the evaporator coils (behind the back inner panel). Heavy solid ice there points straight at a defrost failure. Let it fully thaw 24 hours, plug back in — if it cools then slowly frosts up again, the defrost system needs a part.', difficulty: 'Moderate' },
      { name: 'Stuck or failed evaporator fan', why: 'The evaporator fan pulls cold air across the coils and through the freezer. If it\'s iced up or the motor has failed, the coils get cold but the cold never circulates.', diy: 'With the freezer unplugged, check whether the fan blade spins freely by hand and isn\'t jammed by ice. A grinding or silent fan on a freezer that should be running is a strong clue.', difficulty: 'Moderate' },
      { name: 'Bad compressor start relay', why: 'The start relay kicks the compressor on. When it fails, the compressor either won\'t start or clicks on and off every few minutes — very common on chest and deep freezers. You\'ll often hear a click every 2–5 minutes with no real cooling.', diy: 'Listen for repeated clicking with no steady compressor hum. This is a diagnosis clue only — the relay swap should be done by a tech to confirm the compressor itself is healthy.', difficulty: 'Pro' },
      { name: 'Dirty condenser coils / blocked airflow', why: 'Dust-caked condenser coils or a freezer jammed against a wall can\'t shed heat, so it runs constantly and struggles to hold temperature — worse in a hot garage.', diy: 'Unplug it, vacuum the condenser coils (back or bottom), and give it a few inches of breathing room on all sides.', difficulty: 'Easy' },
      { name: 'Sealed-system leak or dead compressor', why: 'If the coils never get cold and the compressor runs warm, the sealed system may have lost refrigerant or the compressor has failed. This is licensed refrigerant work.', diy: 'Nothing safe to DIY here — recovery, leak repair, and recharge require EPA-608 certification and the right tools.', difficulty: 'Pro' },
    ],
    repairReplace: 'Most freezer failures — defrost parts, relays, thermostats, fans — are inexpensive and well worth fixing, especially since replacing a freezer usually means losing the food inside while you shop. The one to weigh honestly is a sealed-system/compressor repair on a small chest freezer; on a large upright or built-in it\'s usually still worth it, and we\'ll give you the real numbers either way.',
    faqs: [
      { q: 'Why is my freezer running but not freezing?', a: 'The compressor running while nothing freezes points to a defrost failure (frost blocking the coils), a stuck evaporator fan, or a sealed-system problem. Check the coils behind the back panel for heavy ice first — that\'s the most common cause.' },
      { q: 'Why does my chest freezer click but not get cold?', a: 'A click every few minutes with no cooling is the classic sign of a failed compressor start relay. It\'s an affordable, common repair — but the relay should be swapped by a tech to confirm the compressor itself is still good.' },
      { q: 'Is a freezer worth repairing?', a: 'Usually yes. Freezers are simple, durable machines and most repairs cost a fraction of replacement — plus you keep your food. We give you honest repair-vs-replace numbers on your exact model.' },
    ],
  },
  {
    slug: 'ice-maker-not-working',
    appliance: 'Refrigerator',
    question: 'My ice maker isn\'t working — what do I do?',
    metaTitle: 'Ice Maker Not Working? Causes & Fixes From a Real Technician',
    metaDesc: 'A refrigerator ice maker that stopped is usually a frozen fill tube, a bad water inlet valve, a clogged filter, or a failed ice maker module. Here\'s how to tell — and get it fixed.',
    intro: 'A dead ice maker is the single most common refrigerator complaint we see. The good news: the causes are a short, well-understood list, and several of them you can check safely yourself before calling anyone. Here they are in the order a technician works through them.',
    safety: 'Unplug the refrigerator before removing the ice maker or working near the water valve, and shut off the water supply if you disconnect any line.',
    causes: [
      { name: 'Frozen water fill tube', why: 'The small tube that fills the ice mold can freeze shut, usually because the freezer runs a touch too cold or a prior fill dribbled and froze. Water can\'t reach the mold, so no ice.', diy: 'Unplug the fridge, find the fill tube at the back of the ice maker, and gently thaw the ice plug with a hair dryer on low or a cup of warm water. If ice returns after a few days, the underlying cause needs a tech.', difficulty: 'Easy' },
      { name: 'Clogged or overdue water filter', why: 'A water filter that\'s past due chokes water flow to the ice maker (and dispenser). Low flow means small cubes, hollow cubes, or no ice at all.', diy: 'Replace the water filter if it\'s more than ~6 months old and see if flow returns. This is the cheapest thing to rule out first.', difficulty: 'Easy' },
      { name: 'Failed water inlet valve', why: 'The inlet valve opens to let water into the ice maker. It needs adequate household water pressure to work; when it fails or pressure is low, the mold never fills.', diy: 'Check that the saddle valve or shutoff behind/under the fridge is fully open and the line isn\'t kinked. The valve replacement itself is a tech job.', difficulty: 'Moderate' },
      { name: 'Ice maker module / motor failure', why: 'The ice maker head contains a small motor and control that cycle the ejector arm and dump the cubes. When the module fails, the maker won\'t harvest even with water present.', diy: 'Confirm the ice maker is switched on and the shutoff arm/paddle isn\'t stuck in the up (off) position. A module swap is a tech job but an affordable, common one.', difficulty: 'Moderate' },
      { name: 'Stuck shutoff arm or control switch', why: 'The wire shutoff arm (or on newer units, an optical/lever sensor) stops ice when the bin is full. If it\'s stuck up or the sensor is dirty, the maker thinks the bin is always full.', diy: 'Make sure the arm is down and moves freely, and clear any ice chunks jamming the bin or sensor.', difficulty: 'Easy' },
    ],
    repairReplace: 'Almost always repair. Fill-tube thaws, filters, inlet valves, and ice maker modules are inexpensive relative to the fridge, and none of them are a reason to replace the appliance. We\'ll pinpoint the exact part so you\'re not throwing money at guesses.',
    faqs: [
      { q: 'Why did my ice maker suddenly stop making ice?', a: 'The most common sudden causes are a frozen fill tube, a water filter that\'s overdue, or a failed water inlet valve. Start by checking that the ice maker is switched on, the shutoff arm is down, and the filter isn\'t past due.' },
      { q: 'Can I fix my ice maker myself?', a: 'You can safely thaw a frozen fill tube, replace the water filter, confirm the water shutoff is open, and make sure the shutoff arm isn\'t stuck. Valve and module replacements are quick tech jobs — send us your model number and we\'ll bring the right part.' },
      { q: 'How much does ice maker repair cost?', a: 'Most ice maker repairs land around $140 flat labor plus the part. A frozen fill tube can be nearly free; a module or inlet valve is an affordable part. Your $50 Quick Check credits toward the repair.' },
    ],
  },
  {
    slug: 'refrigerator-leaking-water',
    appliance: 'Refrigerator',
    question: 'My refrigerator is leaking water — what do I do?',
    metaTitle: 'Refrigerator Leaking Water? Causes & Fixes From a Real Technician',
    metaDesc: 'A refrigerator leaking water on the floor or pooling inside is usually a clogged defrost drain, a water supply line issue, or a cracked drain pan. Here\'s how to tell — and get it fixed.',
    intro: 'Water on the floor or pooling under the crisper drawers has a short list of causes, and a couple are things you can safely check yourself. Here\'s how a technician narrows it down — from the cheapest, most common cause to the ones that need a service call.',
    safety: 'Unplug the refrigerator before working near the drain or water line, and shut off the water supply if you disconnect the line.',
    causes: [
      { name: 'Clogged defrost drain', why: 'This is the #1 cause of water inside the fridge. The drain that carries defrost melt to the pan clogs with ice or gunk, so the water backs up and pools under the crispers or runs out the door.', diy: 'Unplug the fridge, clear the drain hole at the back of the freezer/fresh-food floor, and flush it with warm water and a turkey baster. A recurring clog means a tech should add the factory drain-heater clip.', difficulty: 'Moderate' },
      { name: 'Leaking water supply line or inlet valve', why: 'The plastic or copper line feeding the dispenser/ice maker can crack or loosen at a fitting, or the inlet valve can seep — showing up as water at the back or under the unit.', diy: 'Pull the fridge out, check the line and the shutoff behind it for drips and kinks, and make sure fittings are snug. A cracked line or a leaking valve is a tech replacement.', difficulty: 'Moderate' },
      { name: 'Clogged or frozen water filter housing', why: 'A poorly seated, cracked, or wrong-model water filter can leak inside the housing, dripping down the inside of the fridge.', diy: 'Reseat the filter or install a fresh correct-model one, and check the head for cracks.', difficulty: 'Easy' },
      { name: 'Cracked or overflowing drain pan', why: 'Defrost water lands in a pan under the fridge to evaporate. A cracked pan, or one overwhelmed by a defrost problem, leaves puddles under the unit.', diy: 'With the fridge unplugged and pulled out, inspect the drain pan underneath for cracks or overfilling.', difficulty: 'Moderate' },
      { name: 'Door not sealing / heavy condensation', why: 'A worn door gasket or a door left ajar lets warm humid air in, which condenses and drips — often mistaken for a plumbing leak.', diy: 'Check the gasket for gaps or tears and make sure the door closes flush and level.', difficulty: 'Easy' },
    ],
    repairReplace: 'Essentially always repair. Every common cause of a leaking fridge — a defrost drain, a water line, a filter, a gasket — is an inexpensive fix and never a reason to replace the appliance. The important part is diagnosing which one it is so it doesn\'t keep coming back.',
    faqs: [
      { q: 'Why is my refrigerator leaking water on the floor?', a: 'Water on the floor is usually a leaking water supply line, a cracked or overflowing drain pan, or a clogged defrost drain backing up. Pull the fridge out and check the line and pan behind it first.' },
      { q: 'Why is there water pooling inside my fridge under the drawers?', a: 'Water pooling under the crisper drawers is the classic sign of a clogged defrost drain. Unplugging the fridge and flushing the drain at the back of the freezer floor with warm water clears most cases.' },
      { q: 'Is a leaking refrigerator worth fixing?', a: 'Yes — every common cause is a low-cost repair. The value is in diagnosing it correctly so the leak actually stops. Send us your model number and a quick video and we\'ll pinpoint it.' },
    ],
  },
  {
    slug: 'dryer-wont-start',
    appliance: 'Dryer',
    question: 'My dryer won\'t start — what do I do?',
    metaTitle: 'Dryer Won\'t Start? Causes & Fixes From a Real Technician',
    metaDesc: 'A dryer that won\'t start or is dead is usually a door switch, a blown thermal fuse, a failed start switch, or a power/breaker issue. Here\'s how to tell — and get it fixed.',
    intro: 'A dryer that won\'t turn on — no hum, no tumble — comes down to a handful of causes, and a couple are things you can rule out in two minutes before calling anyone. Here\'s the order a technician checks, from the free stuff to the parts that need a service call.',
    safety: 'Unplug the dryer (or switch off its breaker) before opening any panel. A dryer runs on 240V — never poke inside a plugged-in machine.',
    causes: [
      { name: 'Power / tripped breaker', why: 'An electric dryer uses a double breaker; if half trips, the dryer can go completely dead or run without heat. A loose cord or dead outlet does the same.', diy: 'Fully flip the dryer\'s breaker off and back on, and confirm the cord is seated. This is the free first check that fixes a surprising number of "dead" dryers.', difficulty: 'Easy' },
      { name: 'Failed door switch', why: 'The door switch tells the dryer the door is closed. If it fails, the dryer won\'t start no matter what — and it\'s one of the most common no-start causes.', diy: 'Press the door firmly shut and listen for the click when you open/close it. No click can mean a bad switch. Replacement is a quick tech job.', difficulty: 'Moderate' },
      { name: 'Blown thermal fuse', why: 'A thermal fuse blows to protect the dryer from overheating — usually caused by a clogged vent. On many models a blown fuse kills the start circuit entirely, so the dryer is dead.', diy: 'A blown thermal fuse almost always means your vent is restricted. Clean the full vent line first; a tech replaces the fuse and confirms airflow so it doesn\'t blow again.', difficulty: 'Moderate' },
      { name: 'Failed start switch or timer/control', why: 'The push-to-start switch or the control board can fail so nothing happens when you press start, even with power and a good door switch.', diy: 'Listen for a faint hum when you hold start — a totally silent press points at the start switch or control. This is a tech diagnosis and repair.', difficulty: 'Moderate' },
      { name: 'Broken belt (with belt switch)', why: 'Some dryers have a belt switch that prevents starting if the belt has snapped, so a broken belt can look like a no-start. You\'ll usually have heard a thump or the drum will spin freely by hand.', diy: 'With the dryer unplugged, reach in and turn the drum — if it spins with no resistance, the belt is likely broken. Belt replacement is a tech job.', difficulty: 'Moderate' },
    ],
    repairReplace: 'Almost always repair. Door switches, thermal fuses, start switches, and belts are all affordable parts, and a no-start dryer is one of the most economical repairs we do. Replacement only enters the picture if it\'s an old machine stacking several failures at once.',
    faqs: [
      { q: 'Why won\'t my dryer turn on at all?', a: 'A completely dead dryer is usually a power/breaker issue or a failed door switch; a dryer that hums but won\'t tumble is often the start switch or a broken belt. Reset the breaker and check for the door-switch click first.' },
      { q: 'Can I fix a dryer that won\'t start myself?', a: 'You can safely reset the breaker, reseat the cord, confirm the door clicks shut, and check the vent for a restriction (the usual cause of a blown thermal fuse). Switch, fuse, and belt replacements are quick tech jobs — unplug it first, it\'s 240V.' },
      { q: 'How much does it cost to fix a dryer that won\'t start?', a: 'Most no-start dryer repairs are around $110 flat labor plus an affordable part. Your $50 Quick Check credits toward the repair, so you never pay for the diagnosis and the fix separately.' },
    ],
  },
];
